In [ ]:
import numpy as np

In [ ]:
import sympy

In [ ]:
def to_subscript(number):
    """Converts an integer or string to its Unicode subscript representation."""
    subscript_map = {
        '0': '₀', '1': '₁', '2': '₂', '3': '₃', '4': '₄',
        '5': '₅', '6': '₆', '7': '₇', '8': '₈', '9': '₉'
    }
    return ''.join(subscript_map.get(digit, digit) for digit in str(number))

In [ ]:
# Global variables to store the current matrix and its dimensions
matrix = None
rows = 0
columns = 0

def create_matrix_interactive():
    global matrix, rows, columns
    print("\n--- Create New Matrix ---")
    while True:
        try:
            rows_input = int(input("Enter the number of rows: "))
            columns_input = int(input("Enter the number of columns: "))
            if rows_input <= 0 or columns_input <= 0:
                print("Dimensions must be positive integers. Please try again.")
            else:
                rows = rows_input
                columns = columns_input
                break
        except ValueError:
            print("Invalid input. Please enter integers for dimensions.")

    matrix_elements = []
    print("Enter elements for the matrix:")
    for r_idx in range(rows):
        for c_idx in range(columns):
            while True:
                try:
                    n = float(input(f"Enter number for C{to_subscript(r_idx)}{to_subscript(c_idx)}: "))
                    matrix_elements.append(n)
                    break
                except ValueError:
                    print("Invalid input. Please enter a numerical value.")

    matrix = np.array(matrix_elements).reshape(rows, columns)
    print("\nYour newly created matrix:")
    print(matrix)

In [ ]:
def check_matrix_equality(mat1, mat2):
    """Checks if two matrices are equal."""
    if np.array_equal(mat1, mat2):
        print("The two matrices are equal.")
    else:
        print("The two matrices are NOT equal.")

In [ ]:
def matrix_two_numerical():
  # Uses global 'rows' and 'columns' from initial matrix definition
  print(matrix)
  print(f"\nEnter elements for the second numerical matrix (dimensions: {rows}x{columns}):")
  matrix_elements_num2 = []
  for r in range(rows):
    for c in range(columns):
      while True:
        try:
          # Prompt for numerical input (int or float)
          val_str = input(f"Enter number for C{to_subscript(r)}{to_subscript(c)}: ")
          val = float(val_str) # Try converting to float to allow decimals
          matrix_elements_num2.append(val)
          break
        except ValueError:
          print("Invalid input. Please enter a numerical value.")

  # Create the numpy array
  matrix_np2 = np.array(matrix_elements_num2).reshape(rows, columns)
  print("\nYour second numerical matrix:")
  print(matrix_np2)
  return matrix_np2

In [ ]:
def matrix_two(rows_dim, columns_dim):
  print(f"\nEnter elements for the second numerical matrix (dimensions: {rows_dim}x{columns_dim}):")
  matrix_elements_num2 = []
  for r in range(rows_dim):
    for c in range(columns_dim):
      while True:
        try:
          val_str = input(f"Enter number for C{to_subscript(r)}{to_subscript(c)}: ")
          val = float(val_str) # Try converting to float to allow decimals
          matrix_elements_num2.append(val)
          break
        except ValueError:
          print("Invalid input. Please enter a numerical value.")

  # Create the numpy array
  matrix_np2 = np.array(matrix_elements_num2).reshape(rows_dim, columns_dim)
  print("\nYour second numerical matrix:")
  print(matrix_np2)
  return matrix_np2

In [ ]:
print(f"C{to_subscript(rows)}{to_subscript(columns)}")

C₀₀


In [ ]:
matrix_elements = []
for r in range(rows):
  for c in range(columns):
    n = int(input(f"Enter number for C{to_subscript(r)}{to_subscript(c)}: "))
    matrix_elements.append(n)

# Reshape the flat list into a NumPy array (matrix)
matrix = np.array(matrix_elements).reshape(rows, columns)
print("Your matrix:")
print(matrix)

Your matrix:
[]


In [ ]:
def type_of_matrix(matrix):
  rows, cols = matrix.shape

  print(f"\nAnalyzing a {rows}x{cols} matrix:")

  # 1. Primary shape classification
  is_square = (rows == cols)
  if is_square:
    print("Matrix is a square matrix.")
  elif rows == 1:
    print("Matrix is a row vector.")
  elif cols == 1:
    print("Matrix is a column vector.")
  else:
    print("Matrix is a rectangular matrix.")

  # 2. Specific property checks using basic NumPy

  # Zero Matrix
  if np.all(matrix == 0):
    print("  - It is a Zero matrix.")

  if is_square: # Properties specifically for square matrices
    # Diagonal Matrix
    is_diagonal = np.all(matrix == np.diag(np.diag(matrix)))
    if is_diagonal:
      print("  - It is a Diagonal matrix.")

      # Scalar Matrix (subset of Diagonal)
      # A scalar matrix has all diagonal elements equal. If it's a non-zero diagonal matrix with equal diagonal elements, it's scalar.
      # A zero matrix is also scalar, but 'Zero matrix' is a more specific classification.
      if np.unique(np.diag(matrix)).size == 1:
        print("  - It is a Scalar matrix.")

        # Identity Matrix (subset of Scalar, where diagonal elements are 1)
        if np.array_equal(matrix, np.identity(rows)):
          print("  - It is an Identity matrix.")

    # Symmetric Matrix
    if np.array_equal(matrix, matrix.T):
      print("  - It is a Symmetric matrix.")

    # Skew-Symmetric Matrix
    if np.array_equal(matrix, -matrix.T):
      print("  - It is a Skew-Symmetric matrix.")

    # Orthogonal Matrix
    # Using np.allclose for floating point comparisons due to potential precision issues.
    if np.allclose(np.dot(matrix, matrix.T), np.identity(rows)):
      print("  - It is an Orthogonal matrix.")

In [ ]:
type_of_matrix(matrix)


Analyzing a 0x0 matrix:
Matrix is a square matrix.
  - It is a Zero matrix.
  - It is a Diagonal matrix.
  - It is a Symmetric matrix.
  - It is a Skew-Symmetric matrix.
  - It is an Orthogonal matrix.


### Symbolic Matrix Equality and Solving for Variables

To solve for unknown variables (like `x` or `y`) in a matrix by equating it with another, we'll use `sympy` to handle symbolic expressions. Let's redefine the second matrix to allow for symbolic entries.

In [ ]:
def matrix_two_for_compare():
  print(matrix)
  # Define symbolic variables
  x, y, z = sympy.symbols('x y z')

  # Re-enter elements for the second matrix, allowing symbolic expressions
  rows2_sym = matrix.shape[0] # Use dimensions from the first matrix
  columns2_sym = matrix.shape[1]

  matrix_elements_sym2 = []
  print(f"\nEnter elements for the second symbolic matrix (dimensions: {rows2_sym}x{columns2_sym}). You can use 'x', 'y', 'z', or numerical values:")
  for r in range(rows2_sym):
    for c in range(columns2_sym):
      # Use eval to convert string input to a sympy expression
      val_str = input(f"Enter expression for C{to_subscript(r)}{to_subscript(c)}: ")
      matrix_elements_sym2.append(sympy.sympify(val_str))

  # Create the sympy Matrix
  matrix_sym2 = sympy.Matrix(matrix_elements_sym2).reshape(rows2_sym, columns2_sym)
  print("\nYour second symbolic matrix:")
  display(matrix_sym2)
  return matrix_sym2

### Set up and Solve the Symbolic Equation

Now, we'll equate the first numerical matrix (converted to a `sympy` matrix) with the second symbolic matrix and solve for any unknown variables.

In [ ]:
# Convert the numerical numpy matrix to a sympy Matrix for comparison
def Compare_Matrices():
  matrix_sym1 = sympy.Matrix(matrix) # This uses the global 'matrix'
  matrix_sym2_received = matrix_two_for_compare() # Call the function, get the returned symbolic matrix

  # Get dimensions from the received symbolic matrix
  rows2_sym, columns2_sym = matrix_sym2_received.shape

  # Create the equation: matrix_sym1 = matrix_sym2_received
  equations = []
  for r in range(rows2_sym):
      for c in range(columns2_sym):
          equations.append(sympy.Eq(matrix_sym1[r, c], matrix_sym2_received[r, c]))

  print("Equations derived from matrix equality:")
  for eq in equations:
      print(eq)

  # Extract all symbols from the equations to solve for
  all_symbols = set()
  for eq in equations:
      all_symbols.update(eq.free_symbols)

  if all_symbols:
      solution = sympy.solve(equations, list(all_symbols))
      if solution:
          print("\nSolution for the variables:")
          display(solution)
      else:
          print("\nNo consistent solution found for the variables.")
  else:
      print("\nNo symbolic variables found in the second matrix to solve for, or the matrices are already fully defined numerically.")
      # If no symbols, check if the numerical matrices are equal
      # Need to convert sympy Matrix to numpy array for np.array_equal
      if np.array_equal(matrix, np.array(matrix_sym2_received).astype(int)):
          print("The two matrices are numerically equal.")
      else:
          print("The two matrices are numerically NOT equal.")

In [ ]:
def add_matrices_numerical():
  # Use the global 'matrix' (which is a numpy array)
  matrix_np1 = matrix

  # Call the new numerical matrix input function
  matrix_np2_for_addition = matrix_two_numerical()

  # Check for dimension compatibility before addition
  if matrix_np1.shape != matrix_np2_for_addition.shape:
    print("Error: Matrices must have the same dimensions for addition.")
    return

  # Perform matrix addition using NumPy
  sum_matrix = matrix_np1 + matrix_np2_for_addition

  print("\nResult of Numerical Matrix Addition (First Matrix + Second Numerical Matrix):")
  print(sum_matrix)

In [ ]:
def subtract_matrices_numerical():
  # Use the global 'matrix' (which is a numpy array)
  matrix_np1 = matrix

  # Call the numerical matrix input function for the second matrix
  matrix_np2_for_subtraction = matrix_two_numerical()

  # Check for dimension compatibility before subtraction
  if matrix_np1.shape != matrix_np2_for_subtraction.shape:
    print("Error: Matrices must have the same dimensions for subtraction.")
    return

  # Perform matrix subtraction using NumPy
  diff_matrix = matrix_np1 - matrix_np2_for_subtraction

  print("\nResult of Numerical Matrix Subtraction (First Matrix - Second Numerical Matrix):")
  print(diff_matrix)

In [ ]:
def scalar_multiplication_numerical():
  # Use the global 'matrix' (which is a numpy array)
  matrix_np = matrix

  print("\nEnter the scalar value for multiplication:")
  while True:
    try:
      scalar_val = float(input("Enter scalar: "))
      break
    except ValueError:
      print("Invalid input. Please enter a numerical value for the scalar.")

  # Perform scalar multiplication using NumPy
  result_matrix = matrix_np * scalar_val

  print(f"\nResult of Scalar Multiplication (\nmatrix * {scalar_val}):")
  print("matrix = ",matrix)
  print(result_matrix)

In [ ]:
def multiply_matrices_numerical():
  # Use the global 'matrix' as the first matrix
  matrix_np1 = matrix
  print("First Matrix:")
  print(matrix_np1)

  # Get dimensions for the second matrix
  # The number of rows of the second matrix must be equal to the number of columns of the first matrix
  rows_mat1, columns_mat1 = matrix_np1.shape
  rows_mat2 = columns_mat1 # Compatibility check: rows of B must equal columns of A
  columns_mat2 = int(input(f"Enter the number of columns for the second matrix (rows will be {rows_mat2}): "))

  # Call matrix_two to get the second matrix with specified dimensions
  matrix_np2 = matrix_two(rows_mat2, columns_mat2)

  # Perform matrix multiplication using NumPy's dot product
  product_matrix = np.dot(matrix_np1, matrix_np2)

  print("\nResult of Numerical Matrix Multiplication (First Matrix * Second Matrix):")
  print(product_matrix)

In [ ]:
def Transpose():
  matrix1=matrix
  print("First Matrix:")
  print(matrix1)
  transpose_matrix = matrix1.T
  print("\nResult of Transpose:")
  print(transpose_matrix)

In [ ]:
def symmetric_skew_symmetric(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        print("Matrix must be square.")
        return

    transpose = matrix.T

    symmetric = (matrix + transpose) / 2
    skew_symmetric = (matrix - transpose) / 2

    print("Original Matrix:")
    print(matrix)

    print("\nSymmetric Matrix:")
    print(symmetric)

    print("\nSkew-Symmetric Matrix:")
    print(skew_symmetric)

    print("\nSum:")
    print("symmetric + skew_symmetric")

In [ ]:
def Determinant():

    matrix1 = matrix

    print("Matrix:")
    print(matrix1)

    if matrix1.shape[0] != matrix1.shape[1]:
        print("Matrix must be square.")
        return

    determinant = np.linalg.det(matrix1)

    print("\nDeterminant:")
    print(determinant)

In [ ]:
def Area_of_traingle():
  print("(x1,y1) , (x2,y2) and (x3,y3) are points of triangles.")
  x1=int(input("Enter the value of x1: "))
  y1=int(input("Enter the value of y1: "))
  x2=int(input("Enter the value of x2: "))
  y2=int(input("Enter the value of y2: "))
  x3=int(input("Enter the value of x3: "))
  y3=int(input("Enter the value of y3: "))
  # Corrected matrix construction: y3 instead of y2
  a=np.array([[x1,y1,1],[x2,y2,1],[x3,y3,1]])
  # Corrected area calculation: take absolute value of determinant
  area=abs(np.linalg.det(a))/2
  print("Area of triangle is: ",area)

In [ ]:
def minor(matrix, row, column):

    minor_matrix = np.delete(matrix, row, axis=0)
    minor_matrix = np.delete(minor_matrix, column, axis=1)

    return np.linalg.det(minor_matrix)

In [ ]:
def minor_matrix(matrix):

    rows, columns = matrix.shape
    result = np.zeros((rows, columns))

    for i in range(rows):
        for j in range(columns):
            result[i, j] = minor(matrix, i, j)

    return result

In [ ]:
def cofactor(matrix, row, column):

    M = minor(matrix, row, column)

    return (-1) ** (row + column) * M

In [ ]:
def cofactor_matrix(matrix):

    rows, columns = matrix.shape
    result = np.zeros((rows, columns))

    for i in range(rows):
        for j in range(columns):
            result[i, j] = cofactor(matrix, i, j)

    return result

In [ ]:
def Adjoint(matrix):
  matrix1=cofactor_matrix(matrix)
  return matrix1.T

In [ ]:
def Inverse(matrix):


    if matrix.shape[0] != matrix.shape[1]:
        print("Matrix must be square.")
        return

    determinant = np.linalg.det(matrix)

    if np.isclose(determinant, 0):
        print("Matrix is not invertible.")
        return

    inverse_matrix = Adjoint(matrix) / determinant

    print("\nResult of Inverse:")
    print(inverse_matrix)

In [ ]:
def system_of_equations():
  variables=int(input("Enter the number of equations and number of variables in one equation (both are same): "))
  A = []
  for r in range(variables):
    for c in range(variables):
      n = int(input(f"Enter number for C{to_subscript(r)}{to_subscript(c)}: "))
      A.append(n)
  B=[]
  for i in range(variables):
    n = int(input(f"Enter number for B{to_subscript(i)}: "))
    B.append(n)
  A = np.array(A).reshape(variables, variables)

  solution = np.linalg.solve(A, B)

  print("Solution:")
  print(solution)

In [ ]:
def Rank():
    print("Matrix:")
    print(matrix)

    rank = np.linalg.matrix_rank(matrix)

    print("\nRank:")
    print(rank)

## Testing


In [ ]:
add_matrices_numerical()

[[1 2 3]
 [4 5 6]]

Enter elements for the second numerical matrix (dimensions: 2x3):
Enter number for C₀₀: 1
Enter number for C₀₁: 2
Enter number for C₀₂: 3
Enter number for C₁₀: 4
Enter number for C₁₁: 5
Enter number for C₁₂: 6

Your second numerical matrix:
[[1. 2. 3.]
 [4. 5. 6.]]

Result of Numerical Matrix Addition (First Matrix + Second Numerical Matrix):
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [ ]:
subtract_matrices_numerical()

[[1 2 3]
 [4 5 6]]

Enter elements for the second numerical matrix (dimensions: 2x3):
Enter number for C₀₀: 5
Enter number for C₀₁: 4
Enter number for C₀₂: 8
Enter number for C₁₀: 1
Enter number for C₁₁: 3
Enter number for C₁₂: 2

Your second numerical matrix:
[[5. 4. 8.]
 [1. 3. 2.]]

Result of Numerical Matrix Subtraction (First Matrix - Second Numerical Matrix):
[[-4. -2. -5.]
 [ 3.  2.  4.]]


In [ ]:
scalar_multiplication_numerical()


Enter the scalar value for multiplication:
Enter scalar: 5

Result of Scalar Multiplication (
matrix * 5.0):
matrix =  [[1 2 3]
 [4 5 6]]
[[ 5. 10. 15.]
 [20. 25. 30.]]


In [ ]:
Compare_Matrices()

[[1 2 3]
 [4 5 6]]

Enter elements for the second symbolic matrix (dimensions: 2x3). You can use 'x', 'y', 'z', or numerical values:
Enter expression for C₀₀: x
Enter expression for C₀₁: x+1
Enter expression for C₀₂: y
Enter expression for C₁₀: z
Enter expression for C₁₁: y+2
Enter expression for C₁₂: z+2

Your second symbolic matrix:


Matrix([
[x, x + 1,     y],
[z, y + 2, z + 2]])

Equations derived from matrix equality:
Eq(1, x)
Eq(2, x + 1)
Eq(3, y)
Eq(4, z)
Eq(5, y + 2)
Eq(6, z + 2)

Solution for the variables:


{x: 1, y: 3, z: 4}

In [ ]:
multiply_matrices_numerical()

First Matrix:
[[1 2 3]
 [4 5 6]]
Enter the number of columns for the second matrix (rows will be 3): 1

Enter elements for the second numerical matrix (dimensions: 3x1):
Enter number for C₀₀: 2
Enter number for C₁₀: 3
Enter number for C₂₀: 0

Your second numerical matrix:
[[2.]
 [3.]
 [0.]]

Result of Numerical Matrix Multiplication (First Matrix * Second Matrix):
[[ 8.]
 [23.]]


In [ ]:
Transpose()

First Matrix:
[[1 2 3]
 [4 5 6]]

Result of Transpose:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a=np.array([[1,2,3],[2,3,4],[5,6,7]])

In [ ]:
symmetric_skew_symmetric(a)

Original Matrix:
[[1 2 3]
 [2 3 4]
 [5 6 7]]

Symmetric Matrix:
[[1. 2. 4.]
 [2. 3. 5.]
 [4. 5. 7.]]

Skew-Symmetric Matrix:
[[ 0.  0. -1.]
 [ 0.  0. -1.]
 [ 1.  1.  0.]]

Sum:
symmetric + skew_symmetric


In [ ]:
Determinant()

Matrix:
[[1 2 3]
 [4 5 6]]
Matrix must be square.


In [ ]:
Area_of_traingle()


(x1,y1) , (x2,y2) and (x3,y3) are points of triangles.
Enter the value of x1: 1
Enter the value of y1: 2
Enter the value of x2: 3
Enter the value of y2: 4
Enter the value of x3: 3
Enter the value of y3: 0
Area of triangle is:  4.000000000000001


In [ ]:
minor(a,1,2)

np.float64(-3.999999999999999)

In [ ]:
cofactor(a,1,2)

np.float64(3.999999999999999)

In [ ]:
minor_matrix(a)

array([[-3., -6., -3.],
       [-4., -8., -4.],
       [-1., -2., -1.]])

In [ ]:
cofactor_matrix(a)

array([[-3.,  6., -3.],
       [ 4., -8.,  4.],
       [-1.,  2., -1.]])

In [ ]:
Adjoint(a)

array([[-3.,  4., -1.],
       [ 6., -8.,  2.],
       [-3.,  4., -1.]])

In [ ]:
Inverse(a)

Matrix is not invertible.


In [ ]:
system_of_equations()

Enter the number of equations and number of variables in one equation (both are same): 2
Enter number for C₀₀: 1
Enter number for C₀₁: 2
Enter number for C₁₀: 3
Enter number for C₁₁: 4
Enter number for B₀: 2
Enter number for B₁: 5
Solution:
[1.  0.5]


In [ ]:
Rank()

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank:
2


## Matrix Solver Program

Now, let's put it all together into an interactive program!

In [ ]:
def main_menu():
    global matrix # Declare matrix as global to allow modification
    while True:
        print("\n" + "="*20 + " MATRIX SOLVER MENU " + "="*20)
        print("1. Create Matrix")
        print("2. Matrix Classification")
        print("3. Addition")
        print("4. Subtraction")
        print("5. Multiplication")
        print("6. Scalar Multiplication")
        print("7. Transpose")
        print("8. Determinant")
        print("9. Minors & Cofactors (individual element)")
        print("10. Minor Matrix")
        print("11. Cofactor Matrix")
        print("12. Adjoint")
        print("13. Inverse")
        print("14. System of Equations")
        print("15. Rank")
        print("16. Area of Triangle (from coordinates)")
        print("17. Symmetric & Skew-Symmetric Decomposition")
        print("18. Compare Matrices (Symbolic)")
        print("19. Exit")
        print("="*60)

        choice = input("Enter your choice: ")

        if choice == '1':
            create_matrix_interactive()
        elif matrix is None and choice not in ['1', '14', '16', '19']:
            print("Please create a matrix first using option 1, or choose System of Equations (14) / Area of Triangle (16).")
        elif choice == '2':
            type_of_matrix(matrix)
        elif choice == '3':
            add_matrices_numerical()
        elif choice == '4':
            subtract_matrices_numerical()
        elif choice == '5':
            multiply_matrices_numerical()
        elif choice == '6':
            scalar_multiplication_numerical()
        elif choice == '7':
            Transpose()
        elif choice == '8':
            Determinant()
        elif choice == '9':
            if matrix.shape[0] != matrix.shape[1]:
                print("Matrix must be square to calculate minor/cofactor of an individual element.")
                continue
            r_idx = int(input("Enter row index for minor/cofactor (0-indexed): "))
            c_idx = int(input("Enter column index for minor/cofactor (0-indexed): "))
            print(f"Minor of element ({r_idx}, {c_idx}): {minor(matrix, r_idx, c_idx)}")
            print(f"Cofactor of element ({r_idx}, {c_idx}): {cofactor(matrix, r_idx, c_idx)}")
        elif choice == '10':
            if matrix.shape[0] != matrix.shape[1]:
                print("Matrix must be square to calculate the Minor Matrix.")
                continue
            print("Minor Matrix:")
            print(minor_matrix(matrix))
        elif choice == '11':
            if matrix.shape[0] != matrix.shape[1]:
                print("Matrix must be square to calculate the Cofactor Matrix.")
                continue
            print("Cofactor Matrix:")
            print(cofactor_matrix(matrix))
        elif choice == '12':
            Adjoint(matrix)
        elif choice == '13':
            Inverse(matrix)
        elif choice == '14':
            system_of_equations()
        elif choice == '15':
            Rank()
        elif choice == '16':
            Area_of_traingle()
        elif choice == '17':
            symmetric_skew_symmetric(matrix)
        elif choice == '18':
            Compare_Matrices()
        elif choice == '19':
            print("Exiting Matrix Solver. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 19.")

# Call the main menu function to start the program
main_menu()


==================== MATRIX SOLVER MENU ====================
1. Create Matrix
2. Matrix Classification
3. Addition
4. Subtraction
5. Multiplication
6. Scalar Multiplication
7. Transpose
8. Determinant
9. Minors & Cofactors (individual element)
10. Minor Matrix
11. Cofactor Matrix
12. Adjoint
13. Inverse
14. System of Equations
15. Rank
16. Area of Triangle (from coordinates)
17. Symmetric & Skew-Symmetric Decomposition
18. Compare Matrices (Symbolic)
19. Exit
Enter your choice: 1

--- Create New Matrix ---
Enter the number of rows: 3
Enter the number of columns: 3
Enter elements for the matrix:
Enter number for C₀₀: 1
Enter number for C₀₁: 3
Enter number for C₀₂: 2
Enter number for C₁₀: 4
Enter number for C₁₁: 6
Enter number for C₁₂: 5
Enter number for C₂₀: 0
Enter number for C₂₁: 7
Enter number for C₂₂: 0

Your newly created matrix:
[[1. 3. 2.]
 [4. 6. 5.]
 [0. 7. 0.]]

==================== MATRIX SOLVER MENU ====================
1. Create Matrix
2. Matrix Classification
3. Addition
