## ***Restriction of numpy arrays-***

*   All elements of the array must be of the same type of data.
*   Once created, the total size of the array can’t change.
*   The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.








In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]]) # 2-dimensional array
b=np.array([1,2,3,4]) # 1-dimensional array
b,a

(array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [ ]:
# array is also mutable
b[1]=10
b

array([ 1, 10,  3,  4])

In [ ]:
a[:3]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Indexing 2-Dimensional Arrays

NumPy arrays allow for powerful indexing and slicing. Here are some common ways to access parts of a 2D array:


In [ ]:
# Re-initialize 'a' for clarity
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("Original Array 'a':\n", a)

Original Array 'a':
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 1. Accessing a Single Element

To access a single element, you specify the row index and then the column index, separated by a comma (e.g., `array[row_index, column_index]`).

In [ ]:
# Element at row 0, column 1 (value: 2)
print("Element at (0, 1):", a[0, 1])

# Element at row 2, column 3 (value: 12)
print("Element at (2, 3):", a[2, 3])

Element at (0, 1): 2
Element at (2, 3): 12


#### 2. Slicing Rows

You can select a range of rows using the colon operator (`:`). The syntax is `array[start_row:end_row]`. Remember that the `end_row` is exclusive.

In [ ]:
# Select the first two rows (from index 0 up to, but not including, index 2)
print("First two rows (a[0:2]):\n", a[0:2])

# Select all rows from index 1 to the end
print("Rows from index 1 onwards (a[1:]):\n", a[1:])

# Select all rows (equivalent to 'a')
print("All rows (a[:]):\n", a[:])

First two rows (a[0:2]):
 [[1 2 3 4]
 [5 6 7 8]]
Rows from index 1 onwards (a[1:]):
 [[ 5  6  7  8]
 [ 9 10 11 12]]
All rows (a[:]):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 3. Slicing Columns

To select columns, you use a colon for the row dimension (meaning "all rows") and then specify the column slice (e.g., `array[:, start_col:end_col]`).

In [ ]:
# Select all rows, but only the first two columns (from index 0 up to, but not including, index 2)
print(a)
print("All rows, first two columns (a[:, 0:2]):\n", a[:, 0:2])

# Select all rows, columns from index 2 onwards
print("All rows, columns from index 2 onwards (a[:, 2:]):\n", a[:, 2:])

# Select all rows, a single column (e.g., column 1)
print("All rows, column 1 (a[:, 1]):\n", a[:, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
All rows, first two columns (a[:, 0:2]):
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
All rows, columns from index 2 onwards (a[:, 2:]):
 [[ 3  4]
 [ 7  8]
 [11 12]]
All rows, column 1 (a[:, 1]):
 [ 2  6 10]


#### 4. Slicing Both Rows and Columns Simultaneously

You can combine row and column slicing: `array[start_row:end_row, start_col:end_col]`.

In [ ]:
# Select the first two rows and the middle two columns
print(a)
print("First two rows, middle two columns (a[0:2, 1:3]):\n", a[0:2, 1:3])

# Select the last row and the last column
print("Last row, last column (a[-1, -1]):", a[-1, -1])

# Select specific rows and all columns
print("Rows 0 and 2, all columns (a[[0, 2], :]):\n", a[[0, 2], :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First two rows, middle two columns (a[0:2, 1:3]):
 [[2 3]
 [6 7]]
Last row, last column (a[-1, -1]): 12
Rows 0 and 2, all columns (a[[0, 2], :]):
 [[ 1  2  3  4]
 [ 9 10 11 12]]


#### 5. Boolean Indexing

Boolean indexing allows you to select elements based on a condition.

In [ ]:
# Select all elements greater than 7
print(a)
print("Elements greater than 7:\n", a[a > 7])

# Select rows where the first element is greater than equal to 5
print("Rows where first element >= 5:\n", a[a[:, 0] >= 5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Elements greater than 7:
 [ 8  9 10 11 12]
Rows where first element >= 5:
 [[ 5  6  7  8]
 [ 9 10 11 12]]


### Attributes of array
* ndim- The number of dimensiions of a array is contained in ndim
* shape - The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension. (i.e., it give the shape of the array (rows,columns))
* size - the total number of elements.
* dtype - data type of elements in the array. (an array contains only 1 data type.) and also the bit like in the below example it is int64= integer + 64 bit

In [ ]:
a.ndim

2

In [ ]:
b.ndim

1

In [ ]:
a.shape

(3, 4)

In [ ]:
b.shape

(4,)

In [ ]:
a.size

12

In [ ]:
b.size

4

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array 'd':\n", d)
print("Shape of 'd':", d.shape)
print("Dimensions of 'd':", d.ndim)
print('size of d: ', d.size)
print('data type of d: ', d.dtype)

3D Array 'd':
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of 'd': (2, 2, 2)
Dimensions of 'd': 3
size of d:  8
data type of d:  int64


In the example above:
- `d.ndim` is 3, indicating a 3-dimensional array.
- `d.shape` is `(2, 2, 2)`. This means:
  - The first `2` is the 'depth' or number of 2D arrays (layers).
  - The second `2` is the number of rows in each 2D array.
  - The third `2` is the number of columns in each 2D array.

### How to create basic arrays-
* np.zeros() - creates a array of 0, all elements are 0
* np.ones() - creates a array of 1, all elements being 1
* np.empty() - creates an array without initializing its elements, so it contains whatever values happen to already be in that memory. These values can look random, but they are not random numbers generated by NumPy.
* np.arange() - creates a array with range of elements can be evenly spaced or even backward.
* np.linspace() - array with values that are spaced linearly in a specified interval

the first 3 are used to save time and when most of your data is 0 or 1 . but if u want to create something where most of the elements are 0 or 1 and few are different u can create a zero or one array and then u can manually assign values to the elements u want to have some other value for.
* np.empty() is useful when you don't care about the initial values because you're going to fill the array yourself afterward. It can be faster than creating an initialized array because NumPy doesn't spend time setting every element to zero or one.

In [ ]:
np.zeros(2,bool)

array([False, False])

In [ ]:
np.zeros(2,int)

array([0, 0])

In [ ]:
np.zeros(3,str)

array(['', '', ''], dtype='<U1')

In [ ]:
np.zeros(4,float)

array([0., 0., 0., 0.])

Here's how to create a 3-dimensional array using `np.zeros()`:

In [ ]:
three_d_array = np.zeros((2, 3, 4))
print("3D Array:\n", three_d_array)
print("Shape of 3D Array:", three_d_array.shape)
print("Dimensions of 3D Array:", three_d_array.ndim)

3D Array:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Shape of 3D Array: (2, 3, 4)
Dimensions of 3D Array: 3


In the example above, `(2, 3, 4)` means:
- 2 'layers' or 'blocks' (the first dimension)
- Each layer has 3 rows (the second dimension)
- Each row has 4 columns (the third dimension)

You can extend this pattern for even higher dimensions, for example, a 4D array `np.zeros((2, 2, 3, 2))`.

np.ones()

In [ ]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones((5,5),str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [ ]:
np.ones((2,2,3,4), float)

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [ ]:
np.ones((2,2),bool)

array([[ True,  True],
       [ True,  True]])

np.empty()

In [ ]:
np.empty((2,3),bool)

array([[ True,  True,  True],
       [ True, False, False]])

In [ ]:
np.empty((2,2),str) # for str it doesnt associate random string values it just keeps empty string.

array([['', ''],
       ['', '']], dtype='<U1')

In [ ]:
np.empty((2,1),float)

array([[1.06513e-318],
       [0.00000e+000]])

np.arrange()

In [ ]:
np.arange(2,50,4,int) # (first limit, last limit, how many gaps, data type)

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [ ]:
a=np.arange(10,-10,-1,float)

In [ ]:
b=np.reshape(a,(2,2,5))
# we cant create a 2d or more dimensional array using arrange alone but we can use rashape to do it
b

array([[[10.,  9.,  8.,  7.,  6.],
        [ 5.,  4.,  3.,  2.,  1.]],

       [[ 0., -1., -2., -3., -4.],
        [-5., -6., -7., -8., -9.]]])

np.linspace()

In [ ]:
np.linspace(2,20,num=5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [ ]:
np.linspace(2.0,10.0,5)
# the start and stop points can be float but the number should always be integer.

array([ 2.,  4.,  6.,  8., 10.])

### Adding, removing, and sorting elements
* np.sort()
* np.concatenate()

In [ ]:
a

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
       -3., -4., -5., -6., -7., -8., -9.])

In [ ]:
np.sort(a)

array([-9., -8., -7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
b

array([[[10.,  9.,  8.,  7.,  6.],
        [ 5.,  4.,  3.,  2.,  1.]],

       [[ 0., -1., -2., -3., -4.],
        [-5., -6., -7., -8., -9.]]])

In [ ]:
np.sort(b) #sort doesnt sort the whole array it sorts every dimension differently like in this case.

array([[[ 6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.]],

       [[-4., -3., -2., -1.,  0.],
        [-9., -8., -7., -6., -5.]]])

* argsort, which is an indirect sort along a specified axis,

* lexsort, which is an indirect stable sort on multiple keys,

* searchsorted, which will find elements in a sorted array, and

* partition, which is a partial sort.

In [ ]:
np.argsort(b,axis=2)

array([[[4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0]],

       [[4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0]]])

In [ ]:
c=np.array([4,2,3])

In [ ]:
np.argsort(c,axis=0) # it gives indexes of the sorted array instead of the actuall sorted array.

array([1, 2, 0])

In [ ]:
np.lexsort(c)

np.int64(0)

In [ ]:
names = np.array(["A", "B", "C", "D"])
marks = np.array([80, 90, 80, 70])
age = np.array([20, 19, 18, 19])

In [ ]:
np.lexsort((age, marks))

array([3, 2, 0, 1])

lexicographical sorting, similar to how words are sorted in a dictionary. Gives indices for sorting using multiple keys

In [ ]:
d = np.array([10, 20, 30, 40, 50])

np.searchsorted(d, 25)
# It finds the position the given value should be placed at in this array.

np.int64(2)

In [ ]:
x = np.array([1, 12, 9, 4, 10, 6, 3])

np.partition(x, 3)

array([ 1,  3,  4,  6,  9, 10, 12])

In [ ]:
scores = np.array([
    55, 89, 32, 91, 76,
    45, 98, 67, 84, 72,
    61, 95, 40, 88, 79
])

In [ ]:
np.sort(scores)

array([32, 40, 45, 55, 61, 67, 72, 76, 79, 84, 88, 89, 91, 95, 98])

**# Few Examples where partition can be used**

In [ ]:
#5th largest value
print(np.partition(scores, -5)[-5])

88


In [ ]:
transactions = np.random.randint(1, 100000, 1_000_000)

In [ ]:
transactions

array([45895, 92569, 31601, ..., 72025, 46694, 56724])

In [ ]:
sorted_transactions = np.sort(transactions)
top_10 = sorted_transactions[-10:]
print(top_10)

[99999 99999 99999 99999 99999 99999 99999 99999 99999 99999]


In [ ]:
#this can be solved by using a single line
np.partition(transactions, -10)[-10:]

array([99999, 99999, 99999, 99999, 99999, 99999, 99999, 99999, 99999,
       99999])

In [ ]:
#top 10 sorted from largest to smallest
top_10 = np.partition(transactions, -10)[-10:]
top_10 = np.sort(top_10)[::-1] #instead of sorting whole array, this can take lesser time

print(top_10)


[99999 99999 99999 99999 99999 99999 99999 99999 99999 99999]


In [ ]:
#finding smallest K values
distances = np.array([
    34, 12, 87, 5, 45, 23, 9, 67, 3, 19,2,100
])
smallest_3 = np.partition(distances, 3)[:3]

print(smallest_3)

[2 3 5]


In [ ]:
#identify the approximate location of the 90th percentile.
index = int(0.90 * len(distances))
print(index)
p90 = np.partition(distances, index)[index]

print(p90)

10
87


100,000 distances
       ↓
   partition
       ↓
5 smallest distances | remaining 99,995
       ↓
    K nearest

In [ ]:
#to find 5 nearest samllest points to 5
distances = np.array([
    34, 12, 87, 5, 45, 23, 9, 67, 3, 19,2,100
])
k = 5

nearest = np.partition(distances, k)[:k]

print(nearest)

[ 2  3  5  9 12]


In [ ]:
np.sort(distances)

array([  2,   3,   5,   9,  12,  19,  23,  34,  45,  67,  87, 100])

In [ ]:
#to find 5  larget values in the array
distances = np.array([
    34, 12, 87, 5, 45, 23, 9, 67, 3, 19,2,100
])
k = 5

nearest = np.partition(distances, -k)[-k:]

print(nearest)

[ 34  45  67  87 100]


In [ ]:
#5 largest values greater than the value at index 5

value = distances[5]   # 23

larger_values = distances[distances > value]

largest_5 = np.sort(larger_values)[-5:][::-1]

print(largest_5)

[100  87  67  45  34]


Remove extreme values
and you want to identify the lower and upper 1% boundaries.

You don't necessarily need to fully sort one million values.

You can use partitioning to find the elements around those positions.

In [ ]:
data = np.random.normal(50, 10, 1_000_000)
print(data)
n = len(data)
print("length of data",n)
lower_index = int(0.01 * n)
upper_index = int(0.20 * n)
print(f"Lower Index{lower_index} & Upper Index {upper_index}")

lower = np.partition(data, lower_index)[lower_index]
upper = np.partition(data, upper_index)[upper_index]

print("Lower boundary:", lower)
print("Upper boundary:", upper)

[33.57125681 57.81138953 40.70455792 ... 40.93945698 44.7515851
 55.20779623]
length of data 1000000
Lower Index10000 & Upper Index 200000
Lower boundary: 26.73743620698957
Upper boundary: 41.5895263363683


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,30,80,25,49.21])
print(data)
n = len(data)
print("length of data",n)
lower_index = int(0.04 * n)
upper_index = int(0.80 * n)
print(f"Lower Index{lower_index} & Upper Index {upper_index}")

lower = np.partition(data, lower_index)[lower_index]
upper = np.partition(data, upper_index)[upper_index]

print("Lower boundary:", lower)
print("Upper boundary:", upper)

[ 1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   30.   80.
 25.   49.21]
length of data 14
Lower Index0 & Upper Index 11
Lower boundary: 1.0
Upper boundary: 30.0


          1%                    98%                  1%
     ┌──────────┬────────────────────────────────┬──────────┐
     │ EXTREMES │          NORMAL DATA           │ EXTREMES │
     └──────────┴────────────────────────────────┴──────────┘
       10 values                              10 values
             ↑                                      ↑
         lower                                  upper
       boundary                                boundary

In [ ]:
import numpy as np

data = np.array([10, 12, 15, 20, 22, 25, 30, 35, 40, 1000])

lower = np.percentile(data, 10)
upper = np.percentile(data, 90)

filtered_data = data[
    (data >= lower) &
    (data <= upper)
]

print("Original:", data)
print("Lower:", lower)
print("Upper:", upper)
print("Filtered:", filtered_data)

Original: [  10   12   15   20   22   25   30   35   40 1000]
Lower: 11.8
Upper: 135.99999999999966
Filtered: [12 15 20 22 25 30 35 40]


In [ ]:
filtered_data = data[
    (data >= lower) &
    (data <= upper)
]
print(filtered_data)

[12 15 20 22 25 30 35 40]


In [ ]:
y = np.array([15,301, 18, 21, 9, 4, 7, 3, 6])

In [ ]:

import numpy as np

y = np.array([100, 2, 50, 7, 90, 1, 30, 5, 20])

print("Original:", y)
print("Sorted:  ", np.sort(y))
print("Partition:", np.partition(y, 4))

Original: [100   2  50   7  90   1  30   5  20]
Sorted:   [  1   2   5   7  20  30  50  90 100]
Partition: [  1   2   5   7  20  30  50  90 100]


### np.concatenate()

In [ ]:
a

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
       -3., -4., -5., -6., -7., -8., -9.])

In [ ]:
b

array([[[10.,  9.,  8.,  7.,  6.],
        [ 5.,  4.,  3.,  2.,  1.]],

       [[ 0., -1., -2., -3., -4.],
        [-5., -6., -7., -8., -9.]]])

In [ ]:
e=np.linspace(-10,20,20)
e

array([-10.        ,  -8.42105263,  -6.84210526,  -5.26315789,
        -3.68421053,  -2.10526316,  -0.52631579,   1.05263158,
         2.63157895,   4.21052632,   5.78947368,   7.36842105,
         8.94736842,  10.52631579,  12.10526316,  13.68421053,
        15.26315789,  16.84210526,  18.42105263,  20.        ])

In [ ]:
f=np.reshape(e,(2,2,5))

In [ ]:
c

array([4, 2, 3])

In [ ]:
d

array([10, 20, 30, 40, 50])

In [ ]:
np.concatenate((c,d))

array([ 4,  2,  3, 10, 20, 30, 40, 50])

In [ ]:
np.concatenate((a,c), axis=0)

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
       -3., -4., -5., -6., -7., -8., -9.,  4.,  2.,  3.])

In [ ]:
b_f_1=np.concatenate((b,f),axis=1)
b_f_1

array([[[ 10.        ,   9.        ,   8.        ,   7.        ,
           6.        ],
        [  5.        ,   4.        ,   3.        ,   2.        ,
           1.        ],
        [-10.        ,  -8.42105263,  -6.84210526,  -5.26315789,
          -3.68421053],
        [ -2.10526316,  -0.52631579,   1.05263158,   2.63157895,
           4.21052632]],

       [[  0.        ,  -1.        ,  -2.        ,  -3.        ,
          -4.        ],
        [ -5.        ,  -6.        ,  -7.        ,  -8.        ,
          -9.        ],
        [  5.78947368,   7.36842105,   8.94736842,  10.52631579,
          12.10526316],
        [ 13.68421053,  15.26315789,  16.84210526,  18.42105263,
          20.        ]]])

Both b and f are 3-dimensional arrays with a shape of (2, 2, 5). This means they each have 2 'layers', 2 'rows' within each layer, and 5 'columns' in each row.

When axis=1 is specified for a 3D array concatenation, it means the arrays are joined along their second dimension (the 'rows'). The number of layers (first dimension) and columns (third dimension) must match for this operation, which they do (2 layers and 5 columns).

The resulting array will have 2 layers, 2 + 2 = 4 rows in each layer, and 5 columns in each row, making its shape (2, 4, 5).



In [ ]:
b_f_2=np.concatenate((b,f),axis=0)
b_f_2

array([[[ 10.        ,   9.        ,   8.        ,   7.        ,
           6.        ],
        [  5.        ,   4.        ,   3.        ,   2.        ,
           1.        ]],

       [[  0.        ,  -1.        ,  -2.        ,  -3.        ,
          -4.        ],
        [ -5.        ,  -6.        ,  -7.        ,  -8.        ,
          -9.        ]],

       [[-10.        ,  -8.42105263,  -6.84210526,  -5.26315789,
          -3.68421053],
        [ -2.10526316,  -0.52631579,   1.05263158,   2.63157895,
           4.21052632]],

       [[  5.78947368,   7.36842105,   8.94736842,  10.52631579,
          12.10526316],
        [ 13.68421053,  15.26315789,  16.84210526,  18.42105263,
          20.        ]]])

### How do you know the shape and size of an array?
* ndarray.ndim -  will tell you the number of axes, or dimensions, of the array.
* ndarray.size - will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.
* ndarray.shape - will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [ ]:
b.ndim

3

In [ ]:
b.size

20

In [ ]:
b.shape

(2, 2, 5)

In [ ]:
b_f_1.shape

(2, 4, 5)

In [ ]:
b_f_2.shape

(4, 2, 5)

### How to convert a 1D array into a 2D array (how to add a new axis to an array)
* np.newaxis - increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array
* np.expand_dims - increase by one at the index we want to increase instead of adding in the last like np.newaxis.

In [ ]:
a

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
       -3., -4., -5., -6., -7., -8., -9.])

In [ ]:
a.shape

(20,)

In [ ]:
a2 = a[np.newaxis, :]
print(a2.shape)
print(a2)

(1, 20)
[[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.  0. -1. -2. -3. -4. -5. -6. -7.
  -8. -9.]]


In [ ]:
a3=a2[np.newaxis, :]
print(a3.shape)
print(a3)

(1, 1, 20)
[[[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.  0. -1. -2. -3. -4. -5. -6.
   -7. -8. -9.]]]


In [ ]:
a4=a[: , np.newaxis]
print(a4.shape)
print(a4)

(20, 1)
[[10.]
 [ 9.]
 [ 8.]
 [ 7.]
 [ 6.]
 [ 5.]
 [ 4.]
 [ 3.]
 [ 2.]
 [ 1.]
 [ 0.]
 [-1.]
 [-2.]
 [-3.]
 [-4.]
 [-5.]
 [-6.]
 [-7.]
 [-8.]
 [-9.]]


np.expand_dims(a,axis)

In [ ]:
a

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
       -3., -4., -5., -6., -7., -8., -9.])

In [ ]:
np.expand_dims(a,axis=0)

array([[10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
        -3., -4., -5., -6., -7., -8., -9.]])

In [ ]:
b

array([[[10.,  9.,  8.,  7.,  6.],
        [ 5.,  4.,  3.,  2.,  1.]],

       [[ 0., -1., -2., -3., -4.],
        [-5., -6., -7., -8., -9.]]])

In [ ]:
b.shape

(2, 2, 5)

In [ ]:
b1=np.expand_dims(b,axis=(3,1))
b1

array([[[[[10.,  9.,  8.,  7.,  6.]],

         [[ 5.,  4.,  3.,  2.,  1.]]]],



       [[[[ 0., -1., -2., -3., -4.]],

         [[-5., -6., -7., -8., -9.]]]]])

In [ ]:
b1.shape

(2, 1, 2, 1, 5)

In [ ]:
b2=np.expand_dims(b,axis=(3,4))
b2

array([[[[[10.]],

         [[ 9.]],

         [[ 8.]],

         [[ 7.]],

         [[ 6.]]],


        [[[ 5.]],

         [[ 4.]],

         [[ 3.]],

         [[ 2.]],

         [[ 1.]]]],



       [[[[ 0.]],

         [[-1.]],

         [[-2.]],

         [[-3.]],

         [[-4.]]],


        [[[-5.]],

         [[-6.]],

         [[-7.]],

         [[-8.]],

         [[-9.]]]]])

In [ ]:
b2.shape

(2, 2, 5, 1, 1)

## Indexing and Slicing
U can index and slice numpy array similarly to list.

In [ ]:
a

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
       -3., -4., -5., -6., -7., -8., -9.])

In [ ]:
a[1]

np.float64(9.0)

In [ ]:
len(a)

20

In [ ]:
a[0:20]

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
       -3., -4., -5., -6., -7., -8., -9.])

In [ ]:
a[::-1]

array([-9., -8., -7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
a[a>5]

array([10.,  9.,  8.,  7.,  6.])

In [ ]:
a[a<=-5]

array([-5., -6., -7., -8., -9.])

In [ ]:
a[a%2==0]

array([10.,  8.,  6.,  4.,  2.,  0., -2., -4., -6., -8.])

In [ ]:
a[(a//2==3) | (a//2==-3)]

array([ 7.,  6., -5., -6.])

In [ ]:
b

array([[[10.,  9.,  8.,  7.,  6.],
        [ 5.,  4.,  3.,  2.,  1.]],

       [[ 0., -1., -2., -3., -4.],
        [-5., -6., -7., -8., -9.]]])

In [ ]:
np.nonzero(b>5)

(array([0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4]))

In [ ]:
np.nonzero(b<5)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

### Understanding `np.nonzero()` with Boolean Indexing

The `np.nonzero()` function is incredibly useful in NumPy for identifying the indices of elements in an array that are not zero. When used with a boolean condition, it helps pinpoint where that condition evaluates to `True`.

Here's a breakdown of how it works:

1.  **Boolean Condition**: First, a boolean expression (like `b > 5` or `b < 5`) is applied to an array. This operation returns a new array of the same shape, but filled with `True` or `False` values. Each `True` indicates that the element at that position in the original array satisfied the condition, while `False` means it did not.

    *   **Example (`b > 5`)**: For an array `b` containing numbers, `b > 5` would result in a boolean array where `True` marks every position where the original element was greater than 5.

2.  **`np.nonzero()` Application**: When this boolean array is passed to `np.nonzero()`, the function looks for all the `True` values.

3.  **Output**: `np.nonzero()` returns a tuple of arrays, one for each dimension of the input array. Each array in the tuple contains the indices of the elements that were `True` in the corresponding dimension.

    *   **For a 1D array**: If `arr = np.array([1, 0, 5, 0, 8])` and you use `np.nonzero(arr > 0)`, it will return `(array([0, 2, 4]),)` indicating the elements at indices 0, 2, and 4 are greater than 0.

    *   **For a multi-dimensional array (like our `b` array)**: If `b` has a shape of `(depth, row, column)`, `np.nonzero(b < 5)` would return a tuple like `(depth_indices_array, row_indices_array, column_indices_array)`. To find the actual elements that satisfy the condition, you can then use these indices with advanced indexing: `b[depth_indices_array, row_indices_array, column_indices_array]`.

### Visualizing the Boolean Array and `np.nonzero()`

Let's take a simplified example to clearly see how the boolean array is formed and how `np.nonzero()` then uses it.

Consider a simple 1D array `my_array`:

```python
import numpy as np

my_array = np.array([10, 3, 25, 5, 8, 30])
print("Original Array:", my_array)
```

Now, let's apply a condition, say `my_array > 10`:

```python
boolean_condition = my_array > 10
print("Boolean Array (my_array > 10):")
print(boolean_condition)
```

**Output:**

```
Original Array: [10  3 25  5  8 30]
Boolean Array (my_array > 10):
[False False  True False False  True]
```

As you can see, the `boolean_condition` array has `True` where the original element was greater than 10 (at indices 2 and 5) and `False` everywhere else.

Finally, when `np.nonzero()` is applied to this boolean array:

```python
indices = np.nonzero(boolean_condition)
print("Indices where condition is True:", indices)
```

**Output:**

```
Indices where condition is True: (array([2, 5]),)
```

`np.nonzero()` returns a tuple containing one array for each dimension. In this 1D case, it returns `(array([2, 5]),)`, which tells us that the elements at index `2` and index `5` in `my_array` satisfied the condition `my_array > 10`.

### Multi-Dimensional Example with `b`

Let's use the `b` array from the notebook:

```python
b = np.array([[[10.,  9.,  8.,  7.,  6.],
               [ 5.,  4.,  3.,  2.,  1.]],

              [[ 0., -1., -2., -3., -4.],
               [-5., -6., -7., -8., -9.]]])
print("Original Array 'b':\n", b)
```

Now, let's apply the condition `b > 5`:

```python
boolean_b_greater_than_5 = b > 5
print("Boolean Array (b > 5):\n", boolean_b_greater_than_5)
```

**Output:**

```
Original Array 'b':
[[[10.  9.  8.  7.  6.]
  [ 5.  4.  3.  2.  1.]]

 [[ 0. -1. -2. -3. -4.]
  [-5. -6. -7. -8. -9.]]]
Boolean Array (b > 5):
[[[ True  True  True  True  True]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]]
```

Here, the `boolean_b_greater_than_5` array clearly shows which elements in `b` are greater than 5. Only the first row of the first 'layer' satisfies this condition.

Finally, applying `np.nonzero()` to this boolean array:

```python
indices_b_gt_5 = np.nonzero(boolean_b_greater_than_5)
print("Indices where condition 'b > 5' is True in 'b':", indices_b_gt_5)
```

**Output:**

```
Indices where condition is True in 'b': (array([0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4]))
```

This tuple of arrays provides the coordinates `(depth, row, column)` for each `True` value. For example, the first set of indices `(0, 0, 0)` corresponds to `b[0, 0, 0]` which is `10.0` (greater than 5).

---

Let's consider another example with the condition `b < 5`:

```python
boolean_b_less_than_5 = b < 5
print("Boolean Array (b < 5):\n", boolean_b_less_than_5)
```

**Output:**

```
Boolean Array (b < 5):
[[[False, False, False, False, False],
  [False,  True,  True,  True,  True]],

 [[ True,  True,  True,  True,  True],
  [ True,  True,  True,  True,  True]]]
```

In this output, you can visually see that the `True` values are located at positions where the original elements in `b` were less than 5.

Now, applying `np.nonzero()` to this `boolean_b_less_than_5` array:

```python
indices_b_lt_5 = np.nonzero(boolean_b_less_than_5)
print("Indices where condition 'b < 5' is True in 'b':", indices_b_lt_5)
```

**Output (as you would get in the console):**

```
Indices where condition 'b < 5' is True in 'b': (array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))
```

This tuple gives the (depth, row, column) indices for all elements in `b` that are less than 5.

### generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them.

In [ ]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(array([10.,  9.,  8.,  7.,  6.]), array([ 0., -1., -2., -3., -4.]))
(array([5., 4., 3., 2., 1.]), array([-5., -6., -7., -8., -9.]))


### Explanation of `zip` with 3D Array Slices

**What is it used for?** This code is used to pair corresponding rows from different 'layers' or 2D slices of a multi-dimensional NumPy array.

**What does it do?**

This snippet effectively takes the first two 'slices' or 2D arrays from your 3D NumPy array `b` (`b[0]` and `b[1]`) and then uses `zip()` to combine their rows.

*   `b[0]` represents the first 2D array (or 'layer') of `b`.
*   `b[1]` represents the second 2D array (or 'layer') of `b`.

The `zip(b[0], b[1])` function works by taking the first row of `b[0]` and pairing it with the first row of `b[1]`, then the second row of `b[0]` with the second row of `b[1]`, and so on.

The `list()` constructor converts this `zip` object into a list of tuples. Each tuple contains two 1D arrays, which are the paired rows.

The `for` loop then iterates through this `list_of_coordinates`, printing each tuple of paired rows, which you can see in the output of the cell above.

# How to create a array from existing data
* slicing and indexing
 * np.vstack()
 * np.hstack()
 * np.hsplit()
 * .view()
 * copy()

In [ ]:
arr1 = a[3:8]
arr1

array([7., 6., 5., 4., 3.])

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((a1, a2)) # stack them vertically

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2)) # stack them horizontally

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3) # split in 3 equall arrays. horizontally

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
np.hsplit(x, (3, 4)) # 3rd and 4th column

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
np.vsplit(x, 2) # vertically

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
np.vsplit(x,(3,5))

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]]),
 array([], shape=(0, 12), dtype=int64),
 array([], shape=(0, 12), dtype=int64)]

In [ ]:
b1 = a[0:10]
b1
b1[0] = 99
b1


array([99.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [ ]:
a

array([99.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
       -3., -4., -5., -6., -7., -8., -9.])

In [ ]:
b2 = a.copy()

In [ ]:
b2

array([99.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.,
       -3., -4., -5., -6., -7., -8., -9.])

In [ ]:
c = a.view()
print(c is a)
print(c.base is a)            # c is a view of the data owned by a
c.flags.owndata
c = c.reshape((2, 10))  # a's shape doesn't change, reassigned c is still a view of a
print(a.shape)
c[0, 4] = 1234         # a's data changes
a

False
True
(20,)


array([ 9.900e+01,  9.000e+00,  8.000e+00,  7.000e+00,  1.234e+03,
        5.000e+00,  4.000e+00,  3.000e+00,  2.000e+00,  1.000e+00,
        0.000e+00, -1.000e+00, -2.000e+00, -3.000e+00, -4.000e+00,
       -5.000e+00, -6.000e+00, -7.000e+00, -8.000e+00, -9.000e+00])

In [ ]:
s = a[1:3]
s[:] = 10  # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
a

array([ 9.900e+01,  1.000e+01,  1.000e+01,  7.000e+00,  1.234e+03,
        5.000e+00,  4.000e+00,  3.000e+00,  2.000e+00,  1.000e+00,
        0.000e+00, -1.000e+00, -2.000e+00, -3.000e+00, -4.000e+00,
       -5.000e+00, -6.000e+00, -7.000e+00, -8.000e+00, -9.000e+00])

In [ ]:
d = a.copy()  # a new array object with new data is created
print(d is a)
print(d.base is a)  # d doesn't share anything with a
d[0] = 9999
a

False
False


array([ 9.900e+01,  1.000e+01,  1.000e+01,  7.000e+00,  1.234e+03,
        5.000e+00,  4.000e+00,  3.000e+00,  2.000e+00,  1.000e+00,
        0.000e+00, -1.000e+00, -2.000e+00, -3.000e+00, -4.000e+00,
       -5.000e+00, -6.000e+00, -7.000e+00, -8.000e+00, -9.000e+00])

## Basic array operations

In [ ]:
a

array([ 9.900e+01,  1.000e+01,  1.000e+01,  7.000e+00,  1.234e+03,
        5.000e+00,  4.000e+00,  3.000e+00,  2.000e+00,  1.000e+00,
        0.000e+00, -1.000e+00, -2.000e+00, -3.000e+00, -4.000e+00,
       -5.000e+00, -6.000e+00, -7.000e+00, -8.000e+00, -9.000e+00])

In [ ]:
e

array([-10.        ,  -8.42105263,  -6.84210526,  -5.26315789,
        -3.68421053,  -2.10526316,  -0.52631579,   1.05263158,
         2.63157895,   4.21052632,   5.78947368,   7.36842105,
         8.94736842,  10.52631579,  12.10526316,  13.68421053,
        15.26315789,  16.84210526,  18.42105263,  20.        ])

In [ ]:
a+e # can add arrays using normal +

array([  89.        ,    1.57894737,    3.15789474,    1.73684211,
       1230.31578947,    2.89473684,    3.47368421,    4.05263158,
          4.63157895,    5.21052632,    5.78947368,    6.36842105,
          6.94736842,    7.52631579,    8.10526316,    8.68421053,
          9.26315789,    9.84210526,   10.42105263,   11.        ])

In [ ]:
a/e

array([-9.90000000e+00, -1.18750000e+00, -1.46153846e+00, -1.33000000e+00,
       -3.34942857e+02, -2.37500000e+00, -7.60000000e+00,  2.85000000e+00,
        7.60000000e-01,  2.37500000e-01,  0.00000000e+00, -1.35714286e-01,
       -2.23529412e-01, -2.85000000e-01, -3.30434783e-01, -3.65384615e-01,
       -3.93103448e-01, -4.15625000e-01, -4.34285714e-01, -4.50000000e-01])

In [ ]:
a-e

array([ 1.09000000e+02,  1.84210526e+01,  1.68421053e+01,  1.22631579e+01,
        1.23768421e+03,  7.10526316e+00,  4.52631579e+00,  1.94736842e+00,
       -6.31578947e-01, -3.21052632e+00, -5.78947368e+00, -8.36842105e+00,
       -1.09473684e+01, -1.35263158e+01, -1.61052632e+01, -1.86842105e+01,
       -2.12631579e+01, -2.38421053e+01, -2.64210526e+01, -2.90000000e+01])

In [ ]:
a*e

array([-9.90000000e+02, -8.42105263e+01, -6.84210526e+01, -3.68421053e+01,
       -4.54631579e+03, -1.05263158e+01, -2.10526316e+00,  3.15789474e+00,
        5.26315789e+00,  4.21052632e+00,  0.00000000e+00, -7.36842105e+00,
       -1.78947368e+01, -3.15789474e+01, -4.84210526e+01, -6.84210526e+01,
       -9.15789474e+01, -1.17894737e+02, -1.47368421e+02, -1.80000000e+02])

In [ ]:
np.sum(a)

np.float64(1330.0)

In [ ]:
b

array([[[ 9.900e+01,  1.000e+01,  1.000e+01,  7.000e+00,  1.234e+03],
        [ 5.000e+00,  4.000e+00,  3.000e+00,  2.000e+00,  1.000e+00]],

       [[ 0.000e+00, -1.000e+00, -2.000e+00, -3.000e+00, -4.000e+00],
        [-5.000e+00, -6.000e+00, -7.000e+00, -8.000e+00, -9.000e+00]]])

In [ ]:
b.sum(axis=1)

array([[ 104.,   14.,   13.,    9., 1235.],
       [  -5.,   -7.,   -9.,  -11.,  -13.]])

## Broadcasting
Normal arithmatic operations are done element by element between two arrays. i.e., both must have same shape. but broadcasting removes this constraint.
* NumPy is smart enough to use the original scalar value without actually making copies so that broadcasting operations are as memory and computationally efficient as possible.

In [ ]:
a

array([ 9.900e+01,  1.000e+01,  1.000e+01,  7.000e+00,  1.234e+03,
        5.000e+00,  4.000e+00,  3.000e+00,  2.000e+00,  1.000e+00,
        0.000e+00, -1.000e+00, -2.000e+00, -3.000e+00, -4.000e+00,
       -5.000e+00, -6.000e+00, -7.000e+00, -8.000e+00, -9.000e+00])

In [ ]:
a*0.5 # broadcasting between an array and a scalar data.
#this saves memory compared t creating another array of the same shape and size as a and putting all values as 0.5 and then multiplying.

array([ 4.95e+01,  5.00e+00,  5.00e+00,  3.50e+00,  6.17e+02,  2.50e+00,
        2.00e+00,  1.50e+00,  1.00e+00,  5.00e-01,  0.00e+00, -5.00e-01,
       -1.00e+00, -1.50e+00, -2.00e+00, -2.50e+00, -3.00e+00, -3.50e+00,
       -4.00e+00, -4.50e+00])

In [ ]:
x1=np.array([1,2,3,4])
x2=np.array([1,2,3])

In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

b = np.array([10, 20, 30, 40])

print(a.shape)
print(b.shape)

print(a + b)

(3, 4)
(4,)
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [ ]:
x=np.array([[1], [2], [3]])
y=np.array([1,2,3,4])
print(x.shape)
print(y.shape) # (4,1)
print(x+y)

(3, 1)
(4,)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


Align shapes from the right. Every pair must be either equal or have a 1.

* (3, 4)   (4,)       ✅
* (3, 1)   (1, 4)     ✅
* (5, 4)   (1, 4)     ✅
* (5, 4)   (3, 4)     ❌ Since this from right its compatible but for broadcasting both left and right should be compatible or right compatible and left 1.
* (3, 4)   (3,)       ❌

To perform element-wise addition, both arrays must have compatible shapes. Since `x1` has 4 elements and `x2` has 3, they are incompatible. We can resolve this by padding `x2` with a value (e.g., 0) to match the length of `x1`.

In [ ]:
x1 = np.array([1,2,3,4])
x2 = np.array([1,2,3])

# Calculate the difference in lengths
diff = len(x1) - len(x2)

# Pad x2 with zeros to match the length of x1
x2_padded = np.pad(x2, (0, diff), 'constant', constant_values=0)

print(f"Original x1: {x1}, shape: {x1.shape}")
print(f"Original x2: {x2}, shape: {x2.shape}")
print(f"Padded x2: {x2_padded}, shape: {x2_padded.shape}")

# Now, addition is possible
result = x1 + x2_padded
print(f"Result of x1 + padded x2: {result}")

Original x1: [1 2 3 4], shape: (4,)
Original x2: [1 2 3], shape: (3,)
Padded x2: [1 2 3 0], shape: (4,)
Result of x1 + padded x2: [2 4 6 4]


Let's explore different `constant_values` for `np.pad`.

In [ ]:

x = np.array([1, 2, 3])

# Pad with a single constant integer
x_padded_int = np.pad(x, (1, 2), mode='constant', constant_values=99)
print(f"Padded with integer 99: {x_padded_int}")

# Pad with a single constant float
x_padded_float = np.pad(x, (2, 1), mode='constant', constant_values=0.5)
print(f"Padded with float 0.5: {x_padded_float}")

# Pad with different constant values for before and after
x_padded_tuple = np.pad(x, (1, 1), mode='constant', constant_values=(-1, -2))
print(f"Padded with tuple (-1, -2): {x_padded_tuple}")

# Example with a boolean array, padding with False
bool_array = np.array([True, False])
bool_padded = np.pad(bool_array, (1, 1), mode='constant', constant_values=False)
print(f"Boolean array padded with False: {bool_padded}")

# Example with a string array, padding with 'X'
str_array = np.array(['a', 'b'], dtype=str)
str_padded = np.pad(str_array, (0, 2), mode='constant', constant_values='X')
print(f"String array padded with 'X': {str_padded}")

Padded with integer 99: [99  1  2  3 99 99]
Padded with float 0.5: [0 0 1 2 3 0]
Padded with tuple (-1, -2): [-1  1  2  3 -2]
Boolean array padded with False: [False  True False False]
String array padded with 'X': ['a' 'b' 'X' 'X']


Beyond `'constant'`, `np.pad` offers several other `mode` options to control how the array is padded. Let's look at some examples.

In [ ]:
x = np.array([1, 2, 3, 4, 5])

print(f"Original array: {x}\n")

# mode='edge': Pad with the edge values of the array.
# Example: [1, 1, 1, 2, 3, 4, 5, 5, 5]
x_padded_edge = np.pad(x, (3, 2), mode='edge')
print(f"Mode 'edge': {x_padded_edge} (3,2)")

# mode='reflect': Pad with the reflection of the vector mirrored on the first and last values.
# Example: [4, 3, 2, 1, 2, 3, 4, 5, 4, 3]
x_padded_reflect = np.pad(x, (3, 2), mode='reflect')
print(f"Mode 'reflect': {x_padded_reflect} (3,2)")

# mode='symmetric': Pad with the reflection of the vector mirrored along the edge of the array.
# Example: [2, 1, 1, 2, 3, 4, 5, 5, 4] (note the slight difference from 'reflect' near edges)
x_padded_symmetric = np.pad(x, (2, 2), mode='symmetric')
print(f"Mode 'symmetric': {x_padded_symmetric} (2,2)")

# mode='wrap': Pad with the wrap around of the vector.
# Example: [3, 4, 5, 1, 2, 3, 4, 5, 1, 2]
x_padded_wrap = np.pad(x, (3, 2), mode='wrap')
print(f"Mode 'wrap': {x_padded_wrap} (3,2)")

# mode='mean': Pad with the mean of all elements of the vector.
# Example: Pad with (1+2+3+4+5)/5 = 3.0
x_padded_mean = np.pad(x, (2, 2), mode='mean')
print(f"Mode 'mean': {x_padded_mean} (2,2)")

# mode='empty': Pad with undefined data (like np.empty()). Often seen when you're just allocating space.
x_padded_empty = np.pad(x, (1, 1), mode='empty')
print(f"Mode 'empty' (values are arbitrary): {x_padded_empty} (1,1)")

Original array: [1 2 3 4 5]

Mode 'edge': [1 1 1 1 2 3 4 5 5 5] (3,2)
Mode 'reflect': [4 3 2 1 2 3 4 5 4 3] (3,2)
Mode 'symmetric': [2 1 1 2 3 4 5 5 4] (2,2)
Mode 'wrap': [3 4 5 1 2 3 4 5 1 2] (3,2)
Mode 'mean': [3 3 1 2 3 4 5 3 3] (2,2)
Mode 'empty' (values are arbitrary): [1 1 2 3 4 5 3] (1,1)


These are some of the most frequently used `mode` options, but there are others like `'median'`, `'maximum'`, `'minimum'`, `'reflect_even'`, `'reflect_odd'`, and more, each with specific behaviors for generating padding values.

### ***vector quantization***

In [ ]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
dist = sqrt(sum(diff**2,axis=-1))
print(argmin(dist))

0


In [ ]:
print('Observation      (1d array):      2 \nCodes            (2d array):  4 x 2\nDiff             (2d array):  4 x 2')

Observation      (1d array):      2 
Codes            (2d array):  4 x 2
Diff             (2d array):  4 x 2


Broadcasting is a powerful tool for writing short and usually intuitive code that does its computations very efficiently in C. However, there are cases when broadcasting uses unnecessarily large amounts of memory for a particular algorithm. In these cases, it is better to write the algorithm’s outer loop in Python. This may also produce more readable code, as algorithms that use broadcasting tend to become more difficult to interpret as the number of dimensions in the broadcast increases.

In [ ]:
import numpy as np

data = np.array([1, 2, 3])
print("max is",data.max())
print("min is",data.min())
print("sum is",data.sum())

max is 3
min is 1
sum is 6


In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
a.min()

np.float64(0.05093587)

In [ ]:
a.max()

np.float64(0.82485143)

In [ ]:
a.sum()

np.float64(4.8595784)

In [ ]:
a.min(axis=0) # axis=0 is vertical

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [ ]:
a.max(axis=1) # axis=1 is horizontal

array([0.5510652 , 0.55645993, 0.82485143])

 all, any, argmax, argmin, argpartition, argsort, choose, clip, compress, copy, cumprod, cumsum, diagonal, imag, max, mean, min, nonzero, partition, prod, put, ravel, real, repeat, reshape, round, searchsorted, sort, squeeze, std, sum, swapaxes, take, trace, transpose, var.

### Array conversion -
* ndarray.item(*args)

Copy an element of an array to a standard Python scalar and return it.

* ndarray.tolist()

Return the array as an a.ndim-levels deep nested list of Python scalars.

* ndarray.tobytes([order])

Construct Python bytes containing the raw data bytes in the array.

* ndarray.tofile(fid, /[, sep, format])

Write array to a file as text or binary (default).

* ndarray.dump(file)

Dump a pickle of the array to the specified file.

* ndarray.dumps()

Returns the pickle of the array as a string.

* ndarray.astype(dtype[, order, casting, ...])

Copy of the array, cast to a specified type.

* ndarray.byteswap([inplace])

Swap the bytes of the array elements

* ndarray.copy([order])

Return a copy of the array.

* ndarray.view([dtype][, type])

New view of array with the same data.

* ndarray.getfield(dtype[, offset])

Returns a field of the given array as a certain type.

* ndarray.setflags([write, align, uic])

Set array flags WRITEABLE, ALIGNED, WRITEBACKIFCOPY, respectively.

* ndarray.fill(value)

Fill the array with a scalar value.

In [ ]:
import numpy as np

# Using a small, simple array for demonstration purposes
demo_arr = np.array([[10, 20], [30, 40]], dtype=np.int64)
print("Array (demo_arr):\n", demo_arr)

Array (demo_arr):
 [[10 20]
 [30 40]]


### `ndarray.item(*args)`
Copies an element of an array to a standard Python scalar and returns it. This is useful when you need to extract a single element from a NumPy array as a native Python type.

In [ ]:
scalar_item = demo_arr[0, 0].item()
print(f"Extracted item from demo_arr[0, 0]: {scalar_item}")
print(f"Type of extracted item: {type(scalar_item)}")

# For a 0-D array (a single number wrapped in an array), you can call .item() directly
zero_d_array = np.array(123)
print(f"\n0-D array: {zero_d_array}")
print(f"Extracted item from 0-D array: {zero_d_array.item()}")

Extracted item from demo_arr[0, 0]: 10
Type of extracted item: <class 'int'>

0-D array: 123
Extracted item from 0-D array: 123


### `ndarray.tolist()`
Returns the array as an `a.ndim`-levels deep nested list of Python scalars. This converts the NumPy array structure into a standard Python list of lists.

In [ ]:
list_version = demo_arr.tolist()
print(f"Array converted to list:\n {list_version}")
print(f"Type of list_version: {type(list_version)}")
print(f"Type of inner element: {type(list_version[0][0])}")

Array converted to list:
 [[10, 20], [30, 40]]
Type of list_version: <class 'list'>
Type of inner element: <class 'int'>


### `ndarray.tobytes([order])`
Constructs Python bytes containing the raw data bytes in the array. This is useful for serializing array data for storage or transmission.

In [ ]:
bytes_version = demo_arr.tobytes()
print(f"Array data as bytes: {bytes_version}")
print(f"Type of bytes_version: {type(bytes_version)}")

# Example with a different order (e.g., Fortran order)
fortran_order_bytes = demo_arr.tobytes(order='F')
print(f"\nArray data as bytes (Fortran order): {fortran_order_bytes}")

Array data as bytes: b'\n\x00\x00\x00\x00\x00\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x1e\x00\x00\x00\x00\x00\x00\x00(\x00\x00\x00\x00\x00\x00\x00'
Type of bytes_version: <class 'bytes'>

Array data as bytes (Fortran order): b'\n\x00\x00\x00\x00\x00\x00\x00\x1e\x00\x00\x00\x00\x00\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00(\x00\x00\x00\x00\x00\x00\x00'


### `ndarray.tofile(fid, /[, sep, format])`
Writes the array to a file as text or binary (default). This is an efficient way to save large arrays to disk.

In [ ]:
# Using a simple 1D array for file writing example
file_arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
file_name_bin = 'array_data.bin'
file_name_txt = 'array_data.txt'

# Write in binary format
file_arr.tofile(file_name_bin)
print(f"Array written to '{file_name_bin}' in binary format.")

# Write in text format with a separator
file_arr.tofile(file_name_txt, sep=',', format='%d')
print(f"Array written to '{file_name_txt}' in text format with comma separation.")

# You can verify by trying to read it back (optional)
# read_back_arr = np.fromfile(file_name_bin, dtype=np.int32)
# print(f"Read back from binary: {read_back_arr}")

Array written to 'array_data.bin' in binary format.
Array written to 'array_data.txt' in text format with comma separation.


### `ndarray.dump(file)`
Dumps a pickle of the array to the specified file. This saves the array object, including its dtype, shape, etc., not just the raw data.

In [ ]:
import pickle

dump_file_name = 'array_dump.pkl'

demo_arr.dump(dump_file_name)
print(f"Array dumped (pickled) to '{dump_file_name}'.")

# To load it back (optional)
# loaded_arr = pickle.load(open(dump_file_name, 'rb'))
# print(f"Loaded array:\n {loaded_arr}")

Array dumped (pickled) to 'array_dump.pkl'.


### `ndarray.dumps()`
Returns the pickle of the array as a string (bytes object). This is similar to `dump` but returns the pickled object as a byte string directly, rather than writing it to a file.

In [ ]:
import pickle

dump_string = demo_arr.dumps()
print(f"Pickled array as a byte string: {dump_string[:50]}...") # Print first 50 chars for brevity
print(f"Type of dump_string: {type(dump_string)}")

# To load it back from the string (optional)
# loaded_from_string_arr = pickle.loads(dump_string)
# print(f"Loaded from string array:\n {loaded_from_string_arr}")

Pickled array as a byte string: b'\x80\x02cnumpy._core.multiarray\n_reconstruct\nq\x00cnumpy\nnd'...
Type of dump_string: <class 'bytes'>


### `ndarray.astype(dtype[, order, casting, ...])`
Returns a copy of the array, cast to a specified type. This is one of the most common conversion methods.

In [ ]:
float_array = demo_arr.astype(np.float32)
print(f"Original array dtype: {demo_arr.dtype}")
print(f"Array cast to float32:\n {float_array}")
print(f"New array dtype: {float_array.dtype}")

bool_array = demo_arr.astype(bool)
print(f"\nArray cast to boolean:\n {bool_array}")
print(f"New array dtype: {bool_array.dtype}")

Original array dtype: int64
Array cast to float32:
 [[10. 20.]
 [30. 40.]]
New array dtype: float32

Array cast to boolean:
 [[ True  True]
 [ True  True]]
New array dtype: bool


### `ndarray.byteswap([inplace])`
Swaps the bytes of the array elements. This is primarily useful when dealing with data that was created on a system with a different byte order (endianness).

In [ ]:
little_endian_arr = np.array([1, 256], dtype='<i2') # Little-endian 2-byte integers
print(f"Original little-endian array: {little_endian_arr} (dtype: {little_endian_arr.dtype})")
print(f"Raw bytes of original: {little_endian_arr.tobytes()}")

swapped_arr = little_endian_arr.byteswap()
print(f"Swapped array: {swapped_arr} (dtype: {swapped_arr.dtype})")
print(f"Raw bytes of swapped: {swapped_arr.tobytes()}")

# You can also swap in place
inplace_arr = np.array([10, 20], dtype='>i4') # Big-endian 4-byte integers
print(f"\nOriginal in-place array: {inplace_arr} (dtype: {inplace_arr.dtype})")
inplace_arr.byteswap(inplace=True)
print(f"In-place swapped array: {inplace_arr}")

Original little-endian array: [  1 256] (dtype: int16)
Raw bytes of original: b'\x01\x00\x00\x01'
Swapped array: [256   1] (dtype: int16)
Raw bytes of swapped: b'\x00\x01\x01\x00'

Original in-place array: [10 20] (dtype: >i4)
In-place swapped array: [167772160 335544320]


### `ndarray.copy([order])`
Returns a copy of the array. This creates a completely independent array with its own data. Changes to the copy will not affect the original.

In [ ]:
original_arr = np.array([1, 2, 3])
copy_arr = original_arr.copy()

print(f"Original array: {original_arr}")
print(f"Copied array: {copy_arr}")

copy_arr[0] = 99

print(f"\nOriginal array after modifying copy: {original_arr} (unchanged)")
print(f"Modified copied array: {copy_arr}")

Original array: [1 2 3]
Copied array: [1 2 3]

Original array after modifying copy: [1 2 3] (unchanged)
Modified copied array: [99  2  3]


### `ndarray.view([dtype][, type])`
Creates a new view of the array with the same data. A view means that the new array shares the same underlying data buffer with the original. Changes made to the view *will* affect the original array.

In [ ]:
original_arr_view = np.array([10, 20, 30])
view_arr = original_arr_view.view()

print(f"Original array: {original_arr_view}")
print(f"View array: {view_arr}")

view_arr[0] = 100

print(f"\nOriginal array after modifying view: {original_arr_view} (changed!)")
print(f"Modified view array: {view_arr}")

# You can also view with a different dtype, reinterpreting the bytes
# (Note: This can lead to unexpected values if dtypes are not compatible in size)
byte_data = np.array([1, 2, 3, 4], dtype=np.int8)
int32_view = byte_data.view(dtype=np.int32)
print(f"\nOriginal byte data: {byte_data}")
print(f"Viewed as int32: {int32_view}")

Original array: [10 20 30]
View array: [10 20 30]

Original array after modifying view: [100  20  30] (changed!)
Modified view array: [100  20  30]

Original byte data: [1 2 3 4]
Viewed as int32: [67305985]


### `ndarray.getfield(dtype[, offset])`
Returns a field of the given array as a certain type. This method is typically used with structured arrays to access individual fields, but can also reinterpret the data type of a regular array's elements. It's similar to `view` but specifically for field access or type reinterpretation.

In [ ]:
# Example with a simple array, reinterpreting its elements as a different type
float_data = np.array([1.5, 2.5], dtype=np.float32)
print(f"Original float array: {float_data} (dtype: {float_data.dtype})")

# Reinterpret the underlying bytes as integers
int_field_view = float_data.getfield(np.int32)
print(f"Reinterpreted as int32: {int_field_view} (dtype: {int_field_view.dtype})")

# Note: For structured arrays, it's used to extract named fields
# For example:
# dt = np.dtype([('name', 'S10'), ('age', 'i4')])
# s_array = np.array([('Alice', 30), ('Bob', 25)], dtype=dt)
# print(s_array.getfield(dtype='i4', offset=10)) # Access 'age' field

Original float array: [1.5 2.5] (dtype: float32)
Reinterpreted as int32: [1069547520 1075838976] (dtype: int32)


### `ndarray.setflags([write, align, uic])`
Sets array flags (e.g., `WRITEABLE`, `ALIGNED`, `WRITEBACKIFCOPY`). This allows you to control properties of the array's memory, such as whether it can be modified. Setting `WRITEABLE` to `False` makes the array read-only.

In [ ]:
modifiable_arr = np.array([1, 2, 3, 4])
print(f"Original array: {modifiable_arr}")
print(f"Is writeable: {modifiable_arr.flags.writeable}")

# Make the array read-only
modifiable_arr.setflags(write=False)
print(f"Is writeable after setflags(write=False): {modifiable_arr.flags.writeable}")

# Attempt to modify the read-only array
try:
    modifiable_arr[0] = 99
except ValueError as e:
    print(f"\nError attempting to modify read-only array: {e}")

# To make it writeable again
modifiable_arr.setflags(write=True)
print(f"Is writeable after setflags(write=True): {modifiable_arr.flags.writeable}")
modifiable_arr[0] = 99 # Now it works
print(f"Array after re-enabling write and modifying: {modifiable_arr}")

Original array: [1 2 3 4]
Is writeable: True
Is writeable after setflags(write=False): False

Error attempting to modify read-only array: assignment destination is read-only
Is writeable after setflags(write=True): True
Array after re-enabling write and modifying: [99  2  3  4]


### `ndarray.fill(value)`
Fills the array with a scalar value. This modifies the array in-place, setting all its elements to the specified value.

In [ ]:
fill_arr = np.array([[1, 2], [3, 4]])
print(f"Original array: {fill_arr}")

fill_arr.fill(0)
print(f"Array after filling with 0:\n {fill_arr}")

fill_arr.fill(7.7)
print(f"Array after filling with 7.7:\n {fill_arr}")

Original array: [[1 2]
 [3 4]]
Array after filling with 0:
 [[0 0]
 [0 0]]
Array after filling with 7.7:
 [[7 7]
 [7 7]]


### Shape manipulation -
* ndarray.reshape(a.reshape)

Returns an array containing the same data with a new shape.

* ndarray.resize(a.resize)

Change shape and size of array in-place.

* ndarray.transpose(*axes)

Returns a view of the array with axes transposed.

* ndarray.swapaxes(axis1, axis2, /)

Return a view of the array with axis1 and axis2 interchanged.

* ndarray.flatten([order])

Return a copy of the array collapsed into one dimension.

* ndarray.ravel([order])

Return a flattened array.

* ndarray.squeeze([axis])

Remove axes of length one from a.

In [ ]:
import numpy as np

# Create a sample 2D array for demonstration
demo_arr_shape = np.arange(1, 13).reshape(3, 4)
print("Original Array (demo_arr_shape):\n", demo_arr_shape)

Original Array (demo_arr_shape):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### `ndarray.reshape(shape)`
Returns an array containing the same data with a new shape. The new shape must be compatible with the original shape (i.e., the total number of elements must remain the same).

In [ ]:
reshaped_array = demo_arr_shape.reshape(4, 3)
print(f"Original shape: {demo_arr_shape.shape}\nOriginal array:\n{demo_arr_shape}")
print(f"\nReshaped to (4, 3): {reshaped_array.shape}\nReshaped array:\n{reshaped_array}")

# You can also reshape to a 1D array
flattened_reshape = demo_arr_shape.reshape(-1)
print(f"\nReshaped to 1D array: {flattened_reshape.shape}\nFlattened array:\n{flattened_reshape}")

Original shape: (3, 4)
Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to (4, 3): (4, 3)
Reshaped array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped to 1D array: (12,)
Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### `ndarray.resize(new_shape, refcheck=True)`
Changes the shape and size of the array *in-place*. If the new array is larger than the original, the new elements are filled with zeros. If it's smaller, elements are truncated. `refcheck=False` can be used to bypass reference checks, which might be necessary in some cases but should be used with caution.

In [ ]:
resize_arr = np.arange(1, 7).reshape(2, 3).copy()
print(f"Original array (resize_arr):\n{resize_arr}\nShape: {resize_arr.shape}")

# Resize to a larger shape (fills with zeros)
resize_arr.resize((3, 3))
print(f"\nResized to (3, 3):\n{resize_arr}\nShape: {resize_arr.shape}")

# Resize to a smaller shape (truncates)
resize_arr.resize((2, 2))
print(f"\nResized to (2, 2):\n{resize_arr}\nShape: {resize_arr.shape}")

# Note: resize modifies the array in-place and returns None.

Original array (resize_arr):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Resized to (3, 3):
[[1 2 3]
 [4 5 6]
 [0 0 0]]
Shape: (3, 3)

Resized to (2, 2):
[[1 2]
 [3 4]]
Shape: (2, 2)


### `ndarray.transpose(*axes)`
Returns a view of the array with axes transposed. For a 2D array, it swaps rows and columns. For higher dimensions, you can specify the new order of axes.

In [ ]:
transposed_array = demo_arr_shape.transpose()
print(f"Original array (demo_arr_shape):\n{demo_arr_shape}\nShape: {demo_arr_shape.shape}")
print(f"\nTransposed array:\n{transposed_array}\nShape: {transposed_array.shape}")

# Example with a 3D array
three_d_arr = np.arange(1, 25).reshape(2, 3, 4)
print(f"\nOriginal 3D array:\n{three_d_arr}\nShape: {three_d_arr.shape}")

# Transpose by reordering axes (e.g., make last axis first)
transposed_3d = three_d_arr.transpose((2, 0, 1))
print(f"\nTransposed 3D array (axes 2,0,1):\n{transposed_3d}\nShape: {transposed_3d.shape}")

Original array (demo_arr_shape):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Shape: (4, 3)

Original 3D array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)

Transposed 3D array (axes 2,0,1):
[[[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]

 [[ 4  8 12]
  [16 20 24]]]
Shape: (4, 2, 3)


### `ndarray.swapaxes(axis1, axis2)`
Returns a view of the array with `axis1` and `axis2` interchanged. This is a specific case of `transpose` for just two axes.

In [ ]:
swapped_axes_array = demo_arr_shape.swapaxes(0, 1)
print(f"Original array (demo_arr_shape):\n{demo_arr_shape}\nShape: {demo_arr_shape.shape}")
print(f"\nArray with axes 0 and 1 swapped:\n{swapped_axes_array}\nShape: {swapped_axes_array.shape}")

# For a 2D array, swapaxes(0, 1) is equivalent to .transpose()

Original array (demo_arr_shape):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

Array with axes 0 and 1 swapped:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Shape: (4, 3)


### `ndarray.flatten([order])`
Returns a *copy* of the array collapsed into one dimension. This always returns a new array, and changes to it will not affect the original.

In [ ]:
flattened_copy = demo_arr_shape.flatten()
print(f"Original array (demo_arr_shape):\n{demo_arr_shape}\nShape: {demo_arr_shape.shape}")
print(f"\nFlattened copy:\n{flattened_copy}\nShape: {flattened_copy.shape}")

# Modify the flattened copy
flattened_copy[0] = 999
print(f"\nModified flattened copy:\n{flattened_copy}")
print(f"Original array after modifying copy (unchanged):\n{demo_arr_shape}")

# You can also specify order ('C' for row-major, 'F' for column-major, 'A' or 'K')
flattened_f_order = demo_arr_shape.flatten(order='F')
print(f"\nFlattened (Fortran order):\n{flattened_f_order}")

Original array (demo_arr_shape):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

Flattened copy:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Modified flattened copy:
[999   2   3   4   5   6   7   8   9  10  11  12]
Original array after modifying copy (unchanged):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened (Fortran order):
[ 1  5  9  2  6 10  3  7 11  4  8 12]


### `ndarray.ravel([order])`
Returns a flattened array. This can return either a view or a copy, depending on whether a view can be created without copying data. If a view is returned, changes to it *will* affect the original array. This is generally preferred over `flatten()` if memory efficiency is critical and you don't need a guaranteed copy.

In [ ]:
raveled_view = demo_arr_shape.ravel()
print(f"Original array (demo_arr_shape):\n{demo_arr_shape}\nShape: {demo_arr_shape.shape}")
print(f"\nRaveled array (potentially a view):\n{raveled_view}\nShape: {raveled_view.shape}")

# Check if it's a view (base will not be None if it's a view)
print(f"Is raveled_view a view? {raveled_view.base is demo_arr_shape}")

# Modify the raveled array
raveled_view[0] = 777
print(f"\nModified raveled array:\n{raveled_view}")
print(f"Original array after modifying raveled array (changed!):\n{demo_arr_shape}")

# Reset demo_arr_shape for next examples
demo_arr_shape = np.arange(1, 13).reshape(3, 4)

Original array (demo_arr_shape):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

Raveled array (potentially a view):
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)
Is raveled_view a view? False

Modified raveled array:
[777   2   3   4   5   6   7   8   9  10  11  12]
Original array after modifying raveled array (changed!):
[[777   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


### `ndarray.squeeze([axis])`
Removes axes of length one from the array. This is useful for reducing the dimensionality of an array that has 'singleton' dimensions (dimensions with size 1).

In [ ]:
# Create an array with singleton dimensions
singleton_arr = np.array([[[1, 2, 3]]])
print(f"Original array (singleton_arr):\n{singleton_arr}\nShape: {singleton_arr.shape}")

# Squeeze all singleton dimensions
squeezed_arr = singleton_arr.squeeze()
print(f"\nSqueezed array (all singleton dimensions removed):\n{squeezed_arr}\nShape: {squeezed_arr.shape}")

# Example with specifying an axis
singleton_arr_axis = np.array([[[10], [20]]]) # Shape (1, 2, 1)
print(f"\nOriginal array (singleton_arr_axis):\n{singleton_arr_axis}\nShape: {singleton_arr_axis.shape}")

# Squeeze only axis 0
squeezed_axis_0 = singleton_arr_axis.squeeze(axis=0)
print(f"\nSqueezed axis 0 only:\n{squeezed_axis_0}\nShape: {squeezed_axis_0.shape}")

# Squeeze only axis 2
squeezed_axis_2 = singleton_arr_axis.squeeze(axis=2)
print(f"\nSqueezed axis 2 only:\n{squeezed_axis_2}\nShape: {squeezed_axis_2.shape}")

Original array (singleton_arr):
[[[1 2 3]]]
Shape: (1, 1, 3)

Squeezed array (all singleton dimensions removed):
[1 2 3]
Shape: (3,)

Original array (singleton_arr_axis):
[[[10]
  [20]]]
Shape: (1, 2, 1)

Squeezed axis 0 only:
[[10]
 [20]]
Shape: (2, 1)

Squeezed axis 2 only:
[[10 20]]
Shape: (1, 2)


### Item selection and manipulation -
* ndarray.take(indices[, axis, out, mode])

Return an array formed from the elements of a at the given indices.

* ndarray.put(indices, values[, mode])

Set a.flat[n] = values[n] for all n in indices.

* ndarray.repeat(repeats[, axis])

Repeat elements of an array.

* ndarray.choose(choices[, out, mode])

Use an index array to construct a new array from a set of choices.

* ndarray.sort([axis, kind, order, stable, ...])

Sort an array in-place.

* ndarray.argsort([axis, kind, order, stable, ...])

Returns the indices that would sort this array.

* ndarray.partition(kth[, axis, kind, order])

Partially sorts the elements in the array in such a way that the value of the element in k-th position is in the position it would be in a sorted array.

* ndarray.argpartition(kth[, axis, kind, order])

Returns the indices that would partition this array.

* ndarray.searchsorted(v[, side, sorter])

Find indices where elements of v should be inserted in a to maintain order.

* ndarray.nonzero()

Return the indices of the elements that are non-zero.

* ndarray.compress(condition[, axis, out])

Return selected slices of this array along given axis.

* ndarray.diagonal([offset, axis1, axis2])

Return specified diagonals.

### `ndarray.take(indices[, axis, out, mode])`
Return an array formed from the elements of `a` at the given `indices`. This is useful for selecting elements along a specific axis.

In [ ]:
print(f"Original array (demo_arr_shape):\n{demo_arr_shape}\n")

# Take elements at specific indices along axis 0 (rows)
taken_rows = demo_arr_shape.take([0, 2], axis=0)
print(f"Taken rows (indices 0 and 2 along axis 0):\n{taken_rows}\n")

# Take elements at specific indices along axis 1 (columns)
taken_cols = demo_arr_shape.take([1, 3], axis=1)
print(f"Taken columns (indices 1 and 3 along axis 1):\n{taken_cols}\n")

# Flatten the array and take elements by flat index
flat_taken = demo_arr_shape.take([0, 5, 11]) # Indices 0, 5, and 11 from the flattened array
print(f"Taken elements by flat indices (0, 5, 11): {flat_taken}")

Original array (demo_arr_shape):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Taken rows (indices 0 and 2 along axis 0):
[[ 1  2  3  4]
 [ 9 10 11 12]]

Taken columns (indices 1 and 3 along axis 1):
[[ 2  4]
 [ 6  8]
 [10 12]]

Taken elements by flat indices (0, 5, 11): [ 1  6 12]


### `ndarray.put(indices, values[, mode])`
Set `a.flat[n] = values[n]` for all `n` in `indices`. This function modifies the array in-place by replacing elements at specified flat indices with new values.

In [ ]:
put_arr = np.arange(1, 10).reshape(3, 3)
print(f"Original array (put_arr):\n{put_arr}\n")

# Change elements at flat indices 0, 4, 8
indices_to_change = [0, 4, 8]
new_values = [99, 88, 77]
put_arr.put(indices_to_change, new_values)
print(f"Array after put (indices 0, 4, 8 with values 99, 88, 77):\n{put_arr}\n")

# Put with more values than indices (values will wrap around)
put_arr_wrap = np.arange(1, 6)
print(f"Original array (put_arr_wrap): {put_arr_wrap}")
put_arr_wrap.put([0, 2], [100, 200, 300]) # 300 is ignored as only 2 indices are given
print(f"Array after put with wrapping values: {put_arr_wrap}")

Original array (put_arr):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after put (indices 0, 4, 8 with values 99, 88, 77):
[[99  2  3]
 [ 4 88  6]
 [ 7  8 77]]

Original array (put_arr_wrap): [1 2 3 4 5]
Array after put with wrapping values: [100   2 200   4   5]


### `ndarray.repeat(repeats[, axis])`
Repeat elements of an array. This can be done along a specific axis or by flattening the array first.

In [ ]:
repeat_arr = np.array([[1, 2], [3, 4]])
print(f"Original array (repeat_arr):\n{repeat_arr}\n")

# Repeat each element 2 times (flattens the array by default)
repeated_flat = repeat_arr.repeat(2)
print(f"Repeated (flat) 2 times: {repeated_flat}\n")

# Repeat each row 3 times (along axis 0)
repeated_axis_0 = repeat_arr.repeat(3, axis=0)
print(f"Repeated rows 3 times (axis=0):\n{repeated_axis_0}\n")

# Repeat each column 2 times (along axis 1)
repeated_axis_1 = repeat_arr.repeat(2, axis=1)
print(f"Repeated columns 2 times (axis=1):\n{repeated_axis_1}\n")

# Repeat with different counts for each element/row/column
# e.g., repeat first element 1 time, second 3 times
repeated_diff_counts = repeat_arr.repeat([1, 3], axis=1)
print(f"Repeated with different counts per column (axis=1, [1,3]):\n{repeated_diff_counts}")

Original array (repeat_arr):
[[1 2]
 [3 4]]

Repeated (flat) 2 times: [1 1 2 2 3 3 4 4]

Repeated rows 3 times (axis=0):
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]

Repeated columns 2 times (axis=1):
[[1 1 2 2]
 [3 3 4 4]]

Repeated with different counts per column (axis=1, [1,3]):
[[1 2 2 2]
 [3 4 4 4]]


### `ndarray.choose(choices[, out, mode])`
Use an index array to construct a new array from a set of choices. Each element of the array acts as an index into the `choices` sequence.

In [ ]:
choices = [[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]]
index_array = np.array([1, 0, 2, 0])
print(f"Index array: {index_array}\n")
print(f"Choices:\n{np.array(choices)}\n")

# Create a new array by choosing from `choices` based on `index_array`
# For each element in `index_array`, it picks the corresponding choice from the same position
chosen_array = index_array.choose(choices)
print(f"Chosen array: {chosen_array}\n")

# Example with a 2D index array
index_2d = np.array([[0, 1], [2, 0]])
print(f"2D Index array:\n{index_2d}\n")
compatible_choices = [
    np.array([[0, 1], [2, 3]]),  # Represents choice 0
    np.array([[10, 11], [12, 13]]), # Represents choice 1
    np.array([[20, 21], [22, 23]])  # Represents choice 2
]

chosen_2d = index_2d.choose(compatible_choices)
print(f"2D Chosen array:\n{chosen_2d}")

Index array: [1 0 2 0]

Choices:
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]

Chosen array: [10  1 22  3]

2D Index array:
[[0 1]
 [2 0]]

2D Chosen array:
[[ 0 11]
 [22  3]]


### `ndarray.sort([axis, kind, order, stable, ...])`
Sort an array in-place. If no axis is specified, the array is flattened and then sorted. When an axis is specified, it sorts along that axis.

In [ ]:
sort_arr = np.array([[3, 1, 2], [6, 5, 4]])
print(f"Original array (sort_arr):\n{sort_arr}\n")

# Sort the entire flattened array (in-place)
original_shape = sort_arr.shape
flattened_sorted = np.sort(sort_arr.ravel())
sort_arr[:] = flattened_sorted.reshape(original_shape)
print(f"Array after sorting flattened (in-place):\n{sort_arr}\n")

# Re-initialize for axis-specific sort
sort_arr = np.array([[3, 1, 2], [6, 5, 4]])

# Sort along axis 0 (columns)
sort_arr.sort(axis=0)
print(f"Array after sorting along axis 0 (columns):\n{sort_arr}\n")

# Re-initialize for axis-specific sort
sort_arr = np.array([[3, 1, 2], [6, 5, 4]])

# Sort along axis 1 (rows)
sort_arr.sort(axis=1)
print(f"Array after sorting along axis 1 (rows):\n{sort_arr}")

Original array (sort_arr):
[[3 1 2]
 [6 5 4]]

Array after sorting flattened (in-place):
[[1 2 3]
 [4 5 6]]

Array after sorting along axis 0 (columns):
[[3 1 2]
 [6 5 4]]

Array after sorting along axis 1 (rows):
[[1 2 3]
 [4 5 6]]


### `ndarray.argsort([axis, kind, order, stable, ...])`
Returns the indices that would sort this array. The original array remains unchanged.

In [ ]:
argsort_arr = np.array([3, 1, 4, 2])
print(f"Original array (argsort_arr): {argsort_arr}\n")

# Get indices that would sort the array
sorted_indices = argsort_arr.argsort()
print(f"Indices that would sort the array: {sorted_indices}\n")
print(f"Original array using sorted indices: {argsort_arr[sorted_indices]}\n")

# Example with 2D array
argsort_2d = np.array([[0.4, 0.1, 0.9], [0.7, 0.3, 0.5]])
print(f"Original 2D array (argsort_2d):\n{argsort_2d}\n")

# Sort along axis 1 (rows)
sorted_indices_axis_1 = argsort_2d.argsort(axis=1)
print(f"Indices that would sort along axis 1:\n{sorted_indices_axis_1}\n")

# Sort along axis 0 (columns)
sorted_indices_axis_0 = argsort_2d.argsort(axis=0)
print(f"Indices that would sort along axis 0:\n{sorted_indices_axis_0}")

Original array (argsort_arr): [3 1 4 2]

Indices that would sort the array: [1 3 0 2]

Original array using sorted indices: [1 2 3 4]

Original 2D array (argsort_2d):
[[0.4 0.1 0.9]
 [0.7 0.3 0.5]]

Indices that would sort along axis 1:
[[1 0 2]
 [1 2 0]]

Indices that would sort along axis 0:
[[0 0 1]
 [1 1 0]]


### `ndarray.partition(kth[, axis, kind, order])`
Partially sorts the elements in the array such that the value of the element in the `k`-th position is in the position it would be in a sorted array. All elements smaller than the `k`-th element are moved before it, and all larger elements are moved after it. The order of elements within the two partitions is not guaranteed.

In [ ]:
partition_arr = np.array([7, 2, 9, 1, 8, 4, 3, 6, 5])
print(f"Original array (partition_arr): {partition_arr}\n")

# Partition around the element that would be at index 4 (0-indexed)
# This means the 5th smallest element will be in its correct sorted position.
partitioned_result = partition_arr.partition(4) # k=4 means the element at index 4 if sorted
print(f"Array after partitioning around index 4: {partitioned_result}\n")

# Verify the element at index 4
fully_sorted = np.sort(partition_arr)
print(f"Fully sorted array: {fully_sorted}")
print(f"Element at index 4 in fully sorted array: {fully_sorted[4]}\n")

# Example with negative kth (for k-th largest elements)
# partition(-k) will place the k-th largest element in its sorted position
partitioned_largest = partition_arr.partition(-3) # 3rd largest element
print(f"Array after partitioning around 3rd largest element (k=-3): {partitioned_largest}\n")
print(f"The 3rd largest element is: {fully_sorted[-3]}")

Original array (partition_arr): [7 2 9 1 8 4 3 6 5]

Array after partitioning around index 4: None

Fully sorted array: [1 2 3 4 5 6 7 8 9]
Element at index 4 in fully sorted array: 5

Array after partitioning around 3rd largest element (k=-3): None

The 3rd largest element is: 7


### `ndarray.argpartition(kth[, axis, kind, order])`
Returns the indices that would partition this array. Similar to `argsort`, but for `partition`.

In [ ]:
argpartition_arr = np.array([7, 2, 9, 1, 8, 4, 3, 6, 5])
print(f"Original array (argpartition_arr): {argpartition_arr}\n")

# Get indices that would partition the array around the element at index 4
partition_indices = argpartition_arr.argpartition(4)
print(f"Indices that would partition around index 4: {partition_indices}\n")
print(f"Array formed using partition indices: {argpartition_arr[partition_indices]}\n")

# Example for finding the indices of the 3 largest elements
largest_3_indices = argpartition_arr.argpartition(-3)[-3:]
print(f"Indices of the 3 largest elements: {largest_3_indices}")
print(f"The 3 largest elements are: {argpartition_arr[largest_3_indices]}")

Original array (argpartition_arr): [7 2 9 1 8 4 3 6 5]

Indices that would partition around index 4: [3 1 6 5 8 7 0 4 2]

Array formed using partition indices: [1 2 3 4 5 6 7 8 9]

Indices of the 3 largest elements: [0 4 2]
The 3 largest elements are: [7 8 9]


### `ndarray.searchsorted(v[, side, sorter])`
Find indices where elements of `v` should be inserted in `a` to maintain order. `a` must be a sorted 1D array.

In [ ]:
sorted_1d_arr = np.array([1, 3, 5, 7, 9])
print(f"Sorted 1D array (sorted_1d_arr): {sorted_1d_arr}\n")

# Find where 6 should be inserted (maintains ascending order)
insert_index_6 = sorted_1d_arr.searchsorted(6)
print(f"Index to insert 6: {insert_index_6}\n")

# Find where multiple values should be inserted
values_to_insert = np.array([0, 4, 8, 10])
insert_indices_multi = sorted_1d_arr.searchsorted(values_to_insert)
print(f"Indices to insert {values_to_insert}: {insert_indices_multi}\n")

# Using 'right' side (insert after equal elements)
insert_index_5_right = sorted_1d_arr.searchsorted(5, side='right')
print(f"Index to insert 5 (side='right'): {insert_index_5_right}")

Sorted 1D array (sorted_1d_arr): [1 3 5 7 9]

Index to insert 6: 3

Indices to insert [ 0  4  8 10]: [0 2 4 5]

Index to insert 5 (side='right'): 3


### `ndarray.nonzero()`
Return the indices of the elements that are non-zero. This function is useful for boolean indexing or for finding the coordinates of specific values.

In [ ]:
nonzero_arr = np.array([[0, 1, 0], [2, 0, 3], [0, 4, 0]])
print(f"Original array (nonzero_arr):\n{nonzero_arr}\n")

# Get row and column indices of non-zero elements
row_indices, col_indices = nonzero_arr.nonzero()
print(f"Row indices of non-zero elements: {row_indices}")
print(f"Column indices of non-zero elements: {col_indices}\n")

# Accessing non-zero elements using these indices
non_zero_elements = nonzero_arr[row_indices, col_indices]
print(f"Non-zero elements: {non_zero_elements}\n")

# Example with a boolean condition
bool_condition = nonzero_arr > 2
print(f"Boolean condition (nonzero_arr > 2):\n{bool_condition}\n")
row_gt_2, col_gt_2 = bool_condition.nonzero()
print(f"Indices where > 2 (row, col): ({row_gt_2}, {col_gt_2})")

Original array (nonzero_arr):
[[0 1 0]
 [2 0 3]
 [0 4 0]]

Row indices of non-zero elements: [0 1 1 2]
Column indices of non-zero elements: [1 0 2 1]

Non-zero elements: [1 2 3 4]

Boolean condition (nonzero_arr > 2):
[[False False False]
 [False False  True]
 [False  True False]]

Indices where > 2 (row, col): ([1 2], [2 1])


### `ndarray.compress(condition[, axis, out])`
Return selected slices of this array along given axis. This is similar to boolean indexing, but you can specify an axis.

In [ ]:
compress_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original array (compress_arr):\n{compress_arr}\n")

# Condition to select rows: select rows where the first element is > 3
row_condition = np.array([False, True, True]) # Select 2nd and 3rd row
compressed_rows = compress_arr.compress(row_condition, axis=0)
print(f"Compressed rows (axis=0, condition [F,T,T]):\n{compressed_rows}\n")

# Condition to select columns: select columns where the element is even
col_condition = np.array([False, True, False]) # Select 2nd column
compressed_cols = compress_arr.compress(col_condition, axis=1)
print(f"Compressed columns (axis=1, condition [F,T,F]):\n{compressed_cols}")

Original array (compress_arr):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Compressed rows (axis=0, condition [F,T,T]):
[[4 5 6]
 [7 8 9]]

Compressed columns (axis=1, condition [F,T,F]):
[[2]
 [5]
 [8]]


### `ndarray.diagonal([offset, axis1, axis2])`
Return specified diagonals. This can extract diagonals from 2D arrays or from arbitrary 2D planes within higher-dimensional arrays.

In [ ]:
diagonal_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original array (diagonal_arr):\n{diagonal_arr}\n")

# Get the main diagonal
main_diagonal = diagonal_arr.diagonal()
print(f"Main diagonal: {main_diagonal}\n")

# Get a diagonal with a positive offset (above the main diagonal)
offset_1_diagonal = diagonal_arr.diagonal(offset=1)
print(f"Diagonal with offset=1: {offset_1_diagonal}\n")

# Get a diagonal with a negative offset (below the main diagonal)
offset_neg_1_diagonal = diagonal_arr.diagonal(offset=-1)
print(f"Diagonal with offset=-1: {offset_neg_1_diagonal}\n")

# Example with a 3D array, extracting diagonals from 2D planes (axis1=0, axis2=1)
three_d_diag_arr = np.arange(1, 28).reshape(3, 3, 3)
print(f"Original 3D array (three_d_diag_arr):\n{three_d_diag_arr}\n")
diag_from_planes = three_d_diag_arr.diagonal(axis1=0, axis2=1)
print(f"Diagonals from planes (axis1=0, axis2=1):\n{diag_from_planes}")

Original array (diagonal_arr):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Main diagonal: [1 5 9]

Diagonal with offset=1: [2 6]

Diagonal with offset=-1: [4 8]

Original 3D array (three_d_diag_arr):
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Diagonals from planes (axis1=0, axis2=1):
[[ 1 13 25]
 [ 2 14 26]
 [ 3 15 27]]


## Creating Matrices
Matrices are 2-d arrays.

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


In [ ]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]


In [ ]:
data = np.array([[1, 2], [3, 4]])
print("data",data)
ones = np.array([[1, 1], [1, 1]])
print("ones",ones)
print(data + ones)

data [[1 2]
 [3 4]]
ones [[1 1]
 [1 1]]
[[2 3]
 [4 5]]


In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
print(np.ones(3))
print(np.zeros(3))
rng = np.random.default_rng()  # the simplest way to generate random numbers
print(rng.random(3))

[1. 1. 1.]
[0. 0. 0.]
[0.3917046  0.26881499 0.14242212]


In [ ]:
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(rng.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.1984253  0.7364877 ]
 [0.77953192 0.23582222]
 [0.95711209 0.30235904]]


# Generating Random Numbers

In [ ]:
rng.integers(5, size=(2, 4))

array([[4, 0, 3, 0],
       [3, 2, 1, 3]])

# How to get unique items and counts
np.unique()

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
unique_values, indices_list = np.unique(a, return_index=True) # to get the indexes of the unique numbers
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [ ]:
unique_values, occurrence_count = np.unique(a, return_counts=True) # returns the count of each numbers
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


for 2d arrays

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [ ]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


# Transposing and reshaping a matrix
arr.reshape(), arr.transpose(), arr.T

In [ ]:
print(data.reshape(2, 3))
print(data.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to Reverse an array

---

np.flip()

---



In [ ]:
np.flip(arr , axis=0)

array([[3, 4, 5],
       [0, 1, 2]])

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.flip(arr, axis=1)

array([[2, 1, 0],
       [5, 4, 3]])

In [ ]:
np.flip(arr[1])

array([5, 4, 3])

In [ ]:
np.flip(arr[:,-1])

array([5, 2])

# Reshaping and flattening multidimensional arrays

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [ ]:
# When you use flatten, changes to your new array won’t change the parent array.
# But when you use ravel, the changes you make to the new array will affect the parent array.

In [ ]:
a1 = arr.flatten()
a1[0] = 99
print(arr)  # Original array
print(a1)  # New array

[[0 1 2]
 [3 4 5]]
[99  1  2  3  4  5]


In [ ]:
a2 = arr.ravel()
a2[0] = 98
print(arr)  # Original array
print(a2)  # New array

[[98  1  2]
 [ 3  4  5]]
[98  1  2  3  4  5]


# How to access the docstring for more information?
help() , ? , ??

In [ ]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.



In [ ]:
max?

In [ ]:
a?

# Copy vs View

### View-
A view is another array object that shares the same underlying data with the original array.

Therefore, modifying the data through the view can modify the original array.

However, if you change the shape of the view, it does not change the shape of the original array. It only changes how the same underlying data is being viewed.
* ndarray.view(): Explicitly creates a new array object looking at the same data.
* Basic Slicing (arr[start:stop:step]): Slicing an array always returns a view.
* np.reshape() / ndarray.reshape(): Changes the shape of an array without changing its data. It returns a view whenever possible (if the memory is contiguous).
* np.ravel(): Flattens an array into a 1D array. It returns a view whenever possible.
* np.squeeze(): Removes single-dimensional entries from the shape of an array (e.g., transforming shape (1, 5) to (5,)) as a view.
* np.swapaxes() / ndarray.swapaxes(): Interchanges two axes of an array as a view.
* np.transpose() / ndarray.T: Permutes the dimensions of an array as a view.

## **Copy-**
A copy is another array that creates its own copy of the data from the original array. Unlike a view, modifications to the copy do not affect the original array.

Creating a copy generally uses more memory than creating a view, but sometimes a copy is necessary when you need the arrays to be independent.

* ndarray.copy(): Explicitly creates a deep copy of the array.

 ### * Advanced/Fancy Indexing:
 Integer Array Indexing (e.g., arr[[0, 2, 4]]) always returns a copy.


 Boolean Mask Indexing (e.g., arr[arr > 5]) always returns a copy.

* ndarray.flatten(): Flattens an array into a 1D array. Unlike ravel(), it always allocates new memory and returns a copy.

* np.astype(): Casts an array to a specified data type (e.g., converting float to int). This almost always copies the data.

### * Structural Modification Functions:
np.append(): Appends values to the end of an array.

np.insert(): Inserts values along a given axis before given indices.

np.delete(): Returns a new array with sub-arrays along an axis deleted.

np.concatenate() / np.vstack() / np.hstack(): Joins a sequence of arrays along an axis into a brand-new array.

* np.unique(): Finds the unique elements of an array and returns them in a sorted, newly allocated 1D array.